### ISSUE TITLE
calendarView.scrollToDate is scrolling to OutDates instead of normal cell

### ISSUE THREAD

**Issue by kreativecoding** [patchthecode/JTAppleCalendar#473] opened 2017-06-30 18:47 UTC
I am currently using the Latest version (7.0.4)

```swift
calendarView.scrollToDate(selectedDate, triggerScrollToDateDelegate: true, animateScroll: true, preferredScrollPosition: nil, extraAddedOffset: 0, completionHandler: {
   self.calendarView.selectDates([selectedDate], triggerSelectionDelegate: true, keepSelectionIfMultiSelectionAllowed: false)
})
```

the selection is correct except that sometimes the collectionview scrolls to the outdate of the previous month instead of the normal month & cell.

Please help, I've tried everything !

**Comment by patchthecode** [comment] 2017-07-02 05:38
@kreativecoding are you sure you are scrolling to the **correct** date?

you are scrolling to `selectedDate`. Can you show the code on how this date is created? 
If you used a `DateFormatter` to create this date, then is the formatter's `locale` and `timezone` the same as the Calendar that you supplied to the `configureCalendar` function?

**Comment by patchthecode** [comment] 2017-07-02 05:39
It will be good if you can join me here -> https://gitter.im/patchthecode/JTAppleCalendar
on my day time. USA/Washington time.

**Comment by grantv9** [comment] 2017-07-09 01:19
@patchthecode I believe I am having the same issue. I am trying to use `scrollToDate` to get to the current month using this code in my `ViewDidLoad`: 
    formatter.dateFormat = "yyyy"
    let currentYear = formatter.string(from: date)
    formatter.dateFormat = "MM"
    let currentMonth = formatter.string(from: date)
  
    formatter.dateFormat = "yyyy MM dd"
    let thisMonth = formatter.date(from: "\(currentYear) \(currentMonth) 01")
    calendarView.scrollToDate(thisMonth!)

When the app runs, it goes to the correct month, but the first few days are from the previous month. Swiping to the next/previous month and back fixes the issue (see the photo - it correctly scrolls to July, but puts the first date on Thursday instead of Sunday.

![jtcalendar example](https://user-images.githubusercontent.com/20562162/27990372-f2ede90c-6422-11e7-90f9-e0d9451d14b3.png)

**Comment by patchthecode** [comment] 2017-07-09 01:33
@grantv9 ok

What is your scrolling mode? `calendarView.scrollingMode = ?`
If it is possible you can present a sample app zipped. Can you just drag the file in this chat box?

**Comment by grantv9** [comment] 2017-07-09 01:43
My scrolling mode is `calendarView.scrollingMode = .stopAtEachCalendarFrameWidth`. I can't zip the app as it is, but I could probably recreate the calendar in a new project if you needed that.

**Comment by grantv9** [comment] 2017-07-09 02:18
@patchthecode  Here's the zip ...but it seems to be scrolling correctly here. All of the calendar related functions are exactly the same here as what I was working on in my other project - the only thing I did was redo the constraints (sorry for it being a bit narrow). Could that be what's messing it up for me?

[Calendar Debug.zip](https://github.com/patchthecode/JTAppleCalendar/files/1133507/Calendar.Debug.zip)

**Comment by patchthecode** [comment] 2017-07-21 06:54
OK. I now have time to look into this.
I'll embed this into a tabbar controller to see the effects.

**Comment by patchthecode** [comment] 2017-08-08 15:38
I looked at this, but could not reproduce it.
Also your sample application behaved correctly. I do not know how it is embedded in the real project inside the tabbar..

**Comment by grantv9** [comment] 2017-08-08 20:46
Sure, I'll upload the new sample app in a bit. Thanks for looking into this

**Comment by patchthecode** [comment] 2017-08-19 03:43
closing until further input provided, then i'll re-open

**Closed by patchthecode** 2017-08-19 03:43 UTC
Labels: Awaiting User Input
