### ISSUE TITLE
Orientation change is reseting the days in the calendar 

### ISSUE THREAD

**Issue by Alvin12344** [patchthecode/JTAppleCalendar#557] opened 2017-09-09 22:30 UTC
It looks like as soon as orientation changes, the calendar resets to the month of end date but does not change the month and year label. That is if I am in June 2017 in landscape and change it to portrait, the days reset to September 2017 but month and label stays as June 2017. How do I stop this from happening?

I am using version 7.0.6 with Swift 3.0

**Comment by patchthecode** [comment] 2017-09-10 06:39
I have a function to help you in that area, but its has a small bug which was fixed by the master branch.
Can you update to master branch code?

put this in pod file
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```
Then do `pod update`.

You will be forced to add a new function called `willDisplayCell`. This is explained [here](https://github.com/patchthecode/JTAppleCalendar/issues/553) under **Problem#1**.

Once your update is complete, lets deal with the rotation problem.
then implement this function in your viewController

```swift
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    let theDate = // the date you want the calendar to focus to on orientation change
    calendarView.viewWillTransition(to: size, with: coordinator, anchorDate: theDate)
}
```

let me know how it goes

**Comment by Alvin12344** [comment] 2017-09-10 18:44
Thanks for your reply, how do I update master branch code? Can you please explain.

**Comment by patchthecode** [comment] 2017-09-10 19:03
I just did above.

put this in pod file

pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'

Then do pod update.

**Comment by Alvin12344** [comment] 2017-09-10 19:18
Got this

Analyzing dependencies
[!] There are multiple dependencies with different sources for `JTAppleCalendar` in `Podfile`:

- JTAppleCalendar (~> 7.0)
- JTAppleCalendar (from `https://github.com/patchthecode/JTAppleCalendar.git`, branch `master`)

**Comment by patchthecode** [comment] 2017-09-10 19:28
can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by josjevv** [comment] 2018-01-15 16:20
I am experiencing this issue with version 7.1.5 (using Carthage).  I added the `viewWillTransition` method (as well as willDisplayCell). The current visibleDates has been lost after rotation and the calendar shows the first date as configured in `configureCalendar` method.

Is it possible this bug has been reintroduced?

**Comment by patchthecode** [comment] 2018-01-15 16:29
@josjevv 

1. Can you show me the code you did?
2. Can you tell me the device you run it on?

**Comment by josjevv** [comment] 2018-01-16 10:46
It's a private repo so I can't easily share the full code base. It's running on iPhone 6s simulator (11.2) but also happens on a real device (also iPhone 6s on 11.2). Relevant code:

set selected date
```
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        self.handleCellConfiguration(cell: cell, cellState: cellState, date: date)
        
        self.selectedDate = date
    }
```

helper function (anchorDate is current selected date)
```
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        if self.calendarView != nil {
            let theDate = self.selectedDate
            NSLog("anchorDate: \(theDate)")
            self.calendarView.viewWillTransition(to: size, with: coordinator, anchorDate: theDate)
        }
    }
```

**Comment by josjevv** [comment] 2018-01-22 09:54
@patchthecode do you have enough information to debug this issue? Thanks in advance.

**Comment by patchthecode** [comment] 2018-01-22 15:59
sorry. i missed this.
let me re-open it.

**Comment by patchthecode** [comment] 2018-01-25 17:39
I am not experiencing the issue that you are facing.
is it possible you can create a new sample project? 
The only code in it can just be that rotation code.

I have tried it in may way on my example project attached to this github project. And I cant reproduce it at all.

**Comment by josjevv** [comment] 2018-01-30 11:19
Hi, 

initially I could not reproduce it either. I kept adding functionality in the example project from the real app. It turns out it starts happening when I added Variations in storyboard based on height. See this example project I have setup for you: https://github.com/SocialSchools/JTAppleCalendarRotationTest

In the (main) storyboard, there is a Main Stack View, which is Vertical by default and Horizontal for compact height only. If I remove that variation, it works fine again. In the real app the events for the selected date is shown.

**Comment by patchthecode** [comment] 2018-02-01 01:32
ok. will take a look.

**Comment by JettF** [comment] 2018-02-06 01:28
I am seeing this issue too. I'll see if I can drum up an example project that replicates it.

**Comment by josjevv** [comment] 2018-02-06 10:11
is the sample project I provided not applicable for you? https://github.com/SocialSchools/JTAppleCalendarRotationTest

**Comment by patchthecode** [comment] 2018-02-06 10:26
It is. I just got super busy this week. 
Will take a look soon ok.

**Comment by josjevv** [comment] 2018-02-06 10:47
hi, sorry the comment was meant for @JettF. Take it easy, I am already glad you can look into it.

**Comment by JettF** [comment] 2018-02-06 23:07
@josjevv after looking at it, your project is applicable to me. My mistake.

**Comment by vldalx** [comment] 2018-03-28 17:10
got the same error in case of device rotation.

**Comment by NWITS** [comment] 2018-04-04 11:08
me too...

**Comment by patchthecode** [comment] 2018-04-04 14:30
checking this out today.

**Comment by patchthecode** [comment] 2018-04-04 15:54
@josjevv sorry i took so long. I got really tied up on other projects.
I see your issue. I'm thinking of a fix. I didnt consider the fact about different size classes.

**Comment by jimmyhiguchi** [comment] 2018-04-18 22:30
I am also experiencing this issue. Let me know if anyone found a work around. Thanks!

**Comment by msencenb** [comment] 2018-05-10 16:34
I ran into this issue too and have a workaround for my situation that others are welcome to use. 

```
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        let selectedDates = JTCalendarView.selectedDates
        if selectedDates.count > 0 {
            JTCalendarView.scrollToDate(selectedDates.first!, animateScroll: false)
            JTCalendarView.selectDates(selectedDates)
        }
    }
```

This works in my case since I select a date (today) when the view is first loaded up. That means selectedDates is guaranteed to have at least one member and the calendar can simply scroll back to it and re-select that date during rotation or size changes.

I am sure there is a more elegant solution that can be made in the internals of JTAppleCalendar, but works ok for my use case. 

P.S. Thank you for such an awesome library @patchthecode , I managed to get a full calendar UI up in just a few days (I was dreading making a custom collectionview)!

**Comment by NickGaens** [comment] 2018-05-25 15:11
@patchthecode Any chance this library will be getting a fix for this issue as it's quite annoying? The workaround of @msencenb above works, but I'd rather not include such a workaround in the first place.

A major thanks as well from me for this awesome library, by the way; it's really great.

**Comment by patchthecode** [comment] 2018-05-25 19:31
@NickGaens 
will work on this. 
i'm just a little caught up at the moment.
but it is on my priority list.

**Comment by jaybayley** [comment] 2018-06-12 00:34
An alternative to @msencenb's solution is:
```
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    super.viewWillTransition(to: size, with: coordinator)
    calendarView.viewWillTransition(to: size, with: coordinator, anchorDate: self.visibleMonthStartDate)
}
```
This worked better in my case as I use the `didSelectDate` delegate method to perform a segue and so don't have any need for `selectedDates`.

**Comment by patchthecode** [comment] 2018-06-12 01:59
@jaybayley 
this is how it is supposed to be done.
but the guys here seem to imply that it is not working.

A sample app was given, above with demonstrated the bug. I have not found a fix yet (sort of caught up between more than one projects)

**Closed** 2018-11-08 15:31 UTC
Labels: Already Fixed on Master Branch
