### ISSUE TITLE
iPhone "On Call" bug confirmed.

### ISSUE THREAD

**Issue by seanrice** [patchthecode/JTAppleCalendar#530] opened 2017-08-11 00:02 UTC
7.0.6 - using non-tableview build ;-) as soon as call answered and app goes to background, calendar loses its place and displays first visible month of calendar startDate. In our case, database and calendar starts at October 2015. This appears to be isolated to CalendarView. All other views are restored properly and reflect state when app was backgrounded.

**Comment by patchthecode** [comment] 2017-08-11 00:44
alright i'll take a look on my device.

**Comment by seanrice** [comment] 2017-08-11 18:02
it should be easy to reproduce using standard storyboard setup, as seen in demos. Here we placed JTAC view in UIVC adding another custom view below. Autolayout connects JTAC bottom to View top, JTAC top to top guide (superview) and View bottom to bottom guide (superview). leading and trailing are connected to superview logically. No magic numbers.

**Comment by patchthecode** [comment] 2017-08-11 18:07
Thanks man.
I didnt get a change to look yesterday, but i'll be more free on weekend sunday time.

**Comment by seanrice** [comment] 2017-08-11 18:13
No rush. Also worth noting, the UIViewController used in above tests is embedded inside a TabBarController and NavigationController.

**Comment by seanrice** [comment] 2017-09-14 04:06
hey pa†ch, any news on this? glad to help as directed.

**Comment by patchthecode** [comment] 2017-09-15 17:23
hey i have not forgotten. 
Just really really tied up, so i had to fix the other worse issues.

But no worries, this issue will be resolved on master branch.
I am doing some code updates there.

**Comment by seanrice** [comment] 2017-09-15 17:32
oh cool. i’d love to know what the issue is / how solved. 
Sean

**Comment by patchthecode** [comment] 2017-09-18 03:00
I was trying to recreate the issue on the latest master branch code. And i could not reproduce it.
I made many enhancements over the time we last spoke. This could have possibly fixed your issue?

here is my test on device.
![bugpossiblyfixed](https://user-images.githubusercontent.com/2439146/30527863-0f8f1c42-9be2-11e7-849e-187c1688effa.gif)

I am not sure if you are using latest master branch code, but if you are, there are 2 very small breaking changes. They are detailed here -> https://github.com/patchthecode/JTAppleCalendar/issues/553

You will have to now include a `willDisplayCell` function unfortunately (thank Apple for that). Unless i can come up with a better way to update already prefetched cells. If you got any issues updating to `master` branch, then let me know.
I'll flag this as fixed for now.

**Comment by seanrice** [comment] 2017-09-18 03:49
Hmmm. Patch, in my tests the app is running, call comes in, and green bar appears upon answering. didn't see the green bar in your animation.

**Comment by patchthecode** [comment] 2017-09-18 05:06
ok let me check

**Comment by seanrice** [comment] 2017-09-18 23:13
STOP THE PRESSES !!! 
Great news. You are correct. It must either be fixed on Master Branch because i can no longer re-create the issue here. JTAppleCalendar is working beautifully inside our tables.

**Comment by patchthecode** [comment] 2017-09-19 01:24
haha. thanks man.
awesome 🍻

**Comment by seanrice** [comment] 2017-09-21 17:44
Bad news. I'm seeing the bug as described. At some point, when our app is backgrounded, its forgetting its current scroll position ... and sliding back to the first date of first month in calendar. It's more cosmetically annoying than anything, but a bugs a bug. Sigh.

**Comment by patchthecode** [comment] 2017-09-21 18:01
Ok, in the mean time before i look into it, can a possible temporary workaround be this?

add code that when coming from background, it scrolls to some saved date. So right before going into background, you save the date. And right as you come to foreground, you scroll to date?

i'll look into this after work.

**Comment by seanrice** [comment] 2017-09-22 17:56
Hmmmm. Interesting. Let me investigate.
Sean

**Comment by HusamAamer** [comment] 2017-10-02 23:15
@patchthecode , I faced the same issue, 
when status bar is in-call status , and app is sent to background then become in foreground again
but the strange thing it didn't occur always !!!!

BTW, Thanks for this great library <3

**Comment by patchthecode** [comment] 2017-10-03 15:47
@HusamAamer does the length of the phone call have something to do with it?

**Comment by patchthecode** [comment] 2018-01-19 16:51
I will close this issue.
It seems to me sometimes when the app comes from the background into the foreground.
For what ever reason, UIKit sends a message to the calendar that its frame has been updated. 
I suspect it might be due to the the top status call bar that appears once there isa phone call.

I think the best approach would be that on coming from back ground, just call `scrollToDate` without animation. Before going to background, save the current date. And after coming from background, scroll to that date.

**Closed by patchthecode** 2018-01-19 16:51 UTC
