### ISSUE TITLE
Calendar Cell Selection Issue?

### ISSUE THREAD

**Issue by iamcastlemin** [patchthecode/JTAppleCalendar#1134] opened 2019-09-16 15:39 UTC
**(Required) Version Number:**
8.0.1

## Description
I have followed the tutorial just as it is, but the cell selection is showing unexpected behaviors. Shown in the GIF, the cells only show the UIView after the cell next to it is selected. How can I resolve this problem?
![ezgif-5-747442aae4a1](https://user-images.githubusercontent.com/52435957/64972031-9c357380-d876-11e9-84cf-e8a53cf425e6.gif)

**Comment by patchthecode** [comment] 2019-09-16 15:48
can you provide me a copy of that sample app?

**Comment by iamcastlemin** [comment] 2019-09-16 16:55
[AvokadoCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/3617296/AvokadoCalendar.zip)

**Comment by patchthecode** [comment] 2019-09-16 17:10
the problem is that you migrated to version 8.0, but forgot to take a look at the [migration guide](https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/).

The names of the `didSelect` and `didDeselect` functions are changed. Therefore according the library, do you not have the `didSelect` and `didDeselect` implemented. Therefore they are not called.

The correct names for them are
```swift
func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath)
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath)
```

Check out the migration guide on the link above to make sure you changed all relevant function names.

Will close this issue now.
have a good one. 🍻

**Closed by patchthecode** 2019-09-16 17:10 UTC
