### ISSUE TITLE
Can't select subclass JTAppleCalendarView in storyboard for my UIView

### ISSUE THREAD

**Issue by Nemely** [patchthecode/JTAppleCalendar#311] opened 2017-02-19 10:24 UTC
Hi,

I'm having issues with what seems like a very simple step. After adding the UIView for the cell and the UIViewController class as well as the UIViewController in the storyboard I try to add a UIView to the storyboard and set the class to JTAppleCalendarView I can't select it from the list. Neither directly nor if I create a new class and subclass JTAppleCalendarView. What step am I missing here?

**Comment by patchthecode** [comment] 2017-02-19 11:38
XCode some times does not autocomplete it.
Just type the name `JTAppleCalendar` and press the `Enter` button.
If you are still having problems, check out the completed tutorial source codes here -> https://github.com/patchthecode/CalendarTutorial

**Comment by Nemely** [comment] 2017-02-19 11:46
I tried that and although the project builds when I open the Viewcontroller the app crashes. I tried restarting Xcode and also cleaning the project but still the same. 

Is there anything else I can try?

**Comment by patchthecode** [comment] 2017-02-19 17:57
@Nemely wait, and you saying that the complete example code here -> https://github.com/patchthecode/CalendarTutorial

Is also crashing??

**Comment by patchthecode** [comment] 2017-02-22 07:44
closing this as I assume the issue is resolved.
If you need more help setting this up then let me know and i will re-open this.

**Closed by patchthecode** 2017-02-22 07:44 UTC
Labels: question
