### ISSUE TITLE
Changing cellSize doesn't update calendar's layout

### ISSUE THREAD

**Issue by itskoBits** [patchthecode/JTAppleCalendar#960] opened 2018-12-31 12:53 UTC
I am using the latest (7.1.6) version of the library.

I noticed that changing the cellSize of the JTAppleCalendarView and calling reloadData() afterwards doesn't update the calendar's layout at all. The issue can be reproduced in the example included with the library. Tapping on the +iSize or -iSize buttons doesn't affect the UI at all.  

![cellsize](https://user-images.githubusercontent.com/4847686/50560658-abd25380-0d0b-11e9-8a01-8bbc5188863f.png)

I tried this example with older versions of the library and it worked as expected with 7.0, 7.1 and 7.1.5. I think the issue was introduced with 7.1.6.

**Comment by patchthecode** [comment] 2018-12-31 16:03
When did you download the sample app?
The version i have with me works as expected :/ 

Can you try redownloading and see if it works?

**Comment by itskoBits** [comment] 2018-12-31 16:19
I got the 7.1.6 version using Carthage.

**Comment by patchthecode** [comment] 2018-12-31 17:04
ok i see the problem....
<img width="380" alt="screen shot 2018-12-31 at 9 04 14 am" src="https://user-images.githubusercontent.com/2439146/50564608-115a1c00-0cdb-11e9-9212-0a53e78ee690.png">


After releasing 7.1.6, i did the fix, but didnt release a 7.1.7 😅

**Comment by patchthecode** [comment] 2018-12-31 17:05
will release today

**Comment by patchthecode** [comment] 2018-12-31 17:08
Wait... scratch that... The code change i made was local to the sample project.
The library is fine.
Can you try downloading the sample project directly from github and see if it works for you?

I want to see where the problem is.

**Comment by patchthecode** [comment] 2019-01-12 18:19
cool. closing this issue then

**Closed by patchthecode** 2019-01-12 18:19 UTC

**Comment by patchthecode** [comment] 2019-01-26 15:59
sorry. i made a mental note to release this but i forgot.
will release it this weekend.

**Comment by bryan1anderson** [comment] 2019-02-25 14:55
@patchthecode did this not get updated? I've been trying to update my pods and 7.1.6 is the current version pods is pulling

**Comment by bryan1anderson** [comment] 2019-02-25 14:58
This is a pretty major issue for me right now. Until you update, do you know of any work arounds? @patchthecode

**Comment by patchthecode** [comment] 2019-02-25 15:58
pushed
