### ISSUE TITLE
Scrolling Problem - Cells give wrong information 

### ISSUE THREAD

**Issue by aliihsanural** [patchthecode/JTAppleCalendar#779] opened 2018-05-11 07:51 UTC
Hi,

I try to catch cells information. In viewDidLoad(), calendar loads dates and prints correct days in handleCellEvents() . But when i scroll the calendar right or left , this prints() doesnt print correct dates. The prints start at the end of the week or start of the week and goes on forward or backward not show the seen dates . Also I try to implements evets week by week .

Is it a bug or my mistake ?

![screen shot 2018-05-11 at 10 45 32](https://user-images.githubusercontent.com/25657842/39912802-8ec71d18-5508-11e8-9406-f4b8abecefb5.png)

    func handleCellEvents(cell: CustomCalendarCell, cellState: CellState) {
        
        formatter.dateFormat = "yyyy MM dd"
        print("handle Cell: \(formatter.string(from: cellState.date)) " )
        cell.eventDotView.isHidden = !eventsFromTheServer.contains { $0.key == formatter.string(from: cellState.date)
        
        }
    }

**Comment by patchthecode** [comment] 2018-05-11 10:34
I am not understand what the problem is.

Can you tell me 
1. what is the expected date you want to see when scrolling?
2. what is the incorrect date that you are seeing?

**Comment by patchthecode** [comment] 2018-05-11 11:40
This library is a UICollectionView subclass. You cannot depend on the `cellForItemAt` function to give you dates that are visible on the screen. Apple has the `UICollectionView` coded efficiently and it will only show new dates as determines by the UICollectionView. We do not have control over this.

If you want to capture visible dates when you scroll, can you use the following function?
```swift
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        // use the `visibleDates` variable here. It will tell you which dates are visible on the screen with each scroll
}
```

Let me know if this helps

**Comment by KrishNaveen** [comment] 2018-05-11 11:52
I tried the above function you suggested it works fine. But I still can see the problem where I tap twice quickly then I am having the issue of seeing old dates.

**Comment by aliihsanural** [comment] 2018-05-11 12:14
@patchthecode didScrollToDateSegmentWith functions starts from Sunday and it starts to show one day before.
Note: I configure calendar with "firstDayOfWeek: DaysOfWeek = .monday"

**Comment by patchthecode** [comment] 2018-05-11 12:36
> didScrollToDateSegmentWith functions starts from Sunday and it starts to show one day before.
Note: I configure calendar with "firstDayOfWeek: DaysOfWeek = .monday"

Can you explain this more?
Hey, I cannot know what the problem is if you just tell me the problem.
You need to tell me

1. What you are seeing
2. What you were expecting

Only then i can know the difference between what you are seeing and what you are expecting.

**Comment by aliihsanural** [comment] 2018-05-11 12:41
You can see the picture at the top that shows firstday is Monday 7 , May. But when i run this code 
print("Visible dates : \(visibleDates.monthDates)") in "didScrollToDateSegmentWith"  , it shows 

"Visible dates : [(date: 2018-05-06 21:00:00 +0000, indexPath: [19, 6]), (date: 2018-05-07 21:00:00 +0000, indexPath: [20, 0]), (date: 2018-05-08 21:00:00 +0000, indexPath: [20, 1]), (date: 2018-05-09 21:00:00 +0000, indexPath: [20, 2]), (date: 2018-05-10 21:00:00 +0000, indexPath: [20, 3]), (date: 2018-05-11 21:00:00 +0000, indexPath: [20, 4]), (date: 2018-05-12 21:00:00 +0000, indexPath: [20, 5])]
"
It starts 2018-05-06 21:00:00 +0000 but i want that 7. The problem is this.

**Comment by patchthecode** [comment] 2018-05-11 18:39
Ok i understand the problem now.
Can you let me know how you are printing the dates to console?

I believe that your problem is this --> https://github.com/patchthecode/JTAppleCalendar/issues/252

It maybe by due to how you are printing the data.
Read the issue and let me know if it makes sense to you.

**Comment by aliihsanural** [comment] 2018-05-14 06:32
Hi again, I think is not a same problem with #252 because that is time zone problem but i get the days wrongly. 

    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        print("Visible dates : \(visibleDates.monthDates)")
        setupViewsOfCalendar(from: visibleDates)
    }

Today 2018-05-14

With this function Print is : 
Visible dates : [(date: 2018-05-13 21:00:00 +0000, indexPath: [20, 6]), (date: 2018-05-14 21:00:00 +0000, indexPath: [21, 0]), (date: 2018-05-15 21:00:00 +0000, indexPath: [21, 1]), (date: 2018-05-16 21:00:00 +0000, indexPath: [21, 2]), (date: 2018-05-17 21:00:00 +0000, indexPath: [21, 3]), (date: 2018-05-18 21:00:00 +0000, indexPath: [21, 4]), (date: 2018-05-19 21:00:00 +0000, indexPath: [21, 5])]

I guess i get these days with +1 Day. No other solution come to my mind.

**Comment by patchthecode** [comment] 2018-05-15 11:04
can you paste me your `configureCalendar` function?
I need to see how you have setup your calendar.

**Comment by patchthecode** [comment] 2018-05-20 01:02
Hey, the best thing to resolve this would be a sample app.
Can you send me a zipped copy of a sample project with the issue?
If i i have a sample project, then i can fix the issue faster.

send to patchthecode@gmail.com and let me know once you do so.
Will close this issue until this is done.

**Comment by aliihsanural** [comment] 2018-05-30 06:38
Its about TimeZone . Its not a bug. Thank you for all replies

**Closed** 2018-05-30 06:38 UTC
Labels: Awaiting User Input
