### ISSUE TITLE
Creating a JTAppleCalendar by Code in MyPlayground

### ISSUE THREAD

**Issue by tibaes** [patchthecode/JTAppleCalendar#246] opened 2016-12-26 16:17 UTC
Xmas people!

Following the question that I created in StackOverflow, I am posting here the issue of creating a JTAppleCalendar (version 6.1.1) directly in Swift 3 code. 
Follows a gist with my playground code:
https://gist.github.com/tibaes/19726f7eb957a6788b72614fed622fe4

The problem is that when setting the calendar.frame, it gets the message: "fatal error: Unexpectedly found nil while unwrapping an Optional value". As I am trying with Playgrounds, I can't monitor exactaly what value is getting nil. However, this message is shown in the following cases: 

1) passing a frame value on constructor, as JTAppleCalendar(frame: someFrameValue)
2) setting the frame value after the constructor, as calendar = JTAppleCalendar(); calendar.frame = someFrameValue 
3) using auto layouts constraints, as calendar = JTAppleCalendar() calendar.heightAnchor.constraint(equalToConstant: 400).isActive = true.

I read some of the JTAppleCalendar code and found that there are actions when the .frame changes, and it is affected by the delegate. However I did not found a solution or explanation to the problem.

[]s

**Comment by patchthecode** [comment] 2016-12-26 18:13
Hi, I am trying to understand your problem.

Is this bug reproducible when you run the application?
Or is it only happening in playground?

And, it it is only happening in playground, then is there a reason you are trying to do this code in playground?

**Comment by patchthecode** [comment] 2016-12-26 18:15
Can you give me an empty sample project with your the playground code failing?
I am trying to setup the code, but I do not know how your code is setup.

**Comment by tibaes** [comment] 2016-12-27 15:04
I uploaded a project with my calendar in playgrounds to my github:
https://github.com/tibaes/swift-calendar

Inside the project, in terminal run pod install to make shure the dependencies are okay. Open the calendar.xcworkspace, build everything via cmd+b, open MyPlaygrounds.playground and run. In the XCode Assistant viewer, you should see a green screen.

The problem can be reproduced modifying the method _ADVCalendarViewController::init(frame: CGRect)_. In the line _let calendar = JTAppleCalendarView()_, you can change to _let calendar = JTAppleCalendarView(frame: frame)_ or change the calendar.frame in any other way to get the message *fatal error: Unexpectedly found nil while unwrapping an Optional value*.

**Comment by patchthecode** [comment] 2016-12-27 21:58
I have deleted all the code in your playground file and I only have this now:

```swift
import UIKit
import Foundation
@testable import JTAppleCalendar

let screen = CGRect(x: 0, y: 0, width: 414, height: 736) // iphone 7 plus
let calendar = JTAppleCalendarView(frame: screen)
```

And still I get the error message: `fatal error: Unexpectedly found nil while unwrapping an Optional value.`

I honestly do not know what the problem is, because this line of code works perfectly outside of playground :/ 

Can I suggest something? Can you try setting up this code normally (outside of playground) and let me know if it works?

There is one thing i see that you are missing. You forgot to register your cell class.

**Comment by patchthecode** [comment] 2017-01-04 06:17
I have not heard a response for 7 days on this.
Closing this as I assume it is resolved.
If it is still a problem for you then re-open this issue

**Closed by patchthecode** 2017-01-04 06:17 UTC

**Comment by tibaes** [comment] 2017-01-08 21:28
I tested outside the playground and it worked after registering the cell class.
Thanks for the help!

**Comment by patchthecode** [comment] 2017-01-08 21:39
Awesome! and thank you for responding again. Glad it worked out.

**Comment by patchthecode** [comment] 2017-01-11 16:01
awesome. cool.
