### ISSUE TITLE
Range with zero spacing between cells issue

### ISSUE THREAD

**Issue by romaHerman** [patchthecode/JTAppleCalendar#538] opened 2017-08-21 14:02 UTC
Hi 

I want to achieve range selection with zero space between cells 
But I have white spaces between cells so sometimes cell occurred to be less in width than others 

I'm not altering cell size programmatically. 

In storyboard I have image with trailing leading bottom and top constraints to cell 
in calendar cell width and height is set up to 50 
and  cell size is 0 (like in example app)  

Maybe I'm missing something when using library or maybe there is some issue for calculating cell width and height (I have tried different ratio for calendar width and height: square and rectangles )

Thanks in advance!

![screen shot 2017-08-21 at 16 50 25](https://user-images.githubusercontent.com/4000453/29522540-32149838-8692-11e7-833f-0b28dcfd9b7e.png)

**Comment by patchthecode** [comment] 2017-08-21 14:15
Yea, the spacing between cells problem is not a calendar issue. It is a UICollectionView issue.
If you try to do a range select on a regular UICollectionView, you will encounter this problem.

This problem occurs because of this: 
we have 7 columns, and a fixed width. Therefore if the width is something like say `414`. The cell's with will = 414 / 7 = 59.1428571429** recurring. That recurring number is what iscausing the thin line space.

To fix, follow these steps:
1. Have your CalendarView **CENTERED** with constraints in the middle of the screen
2. Set a width constraint on it.
3. Create an IBOutlet for the width constraint. Make it = 414 or something.
4. In your viewDidLoad, change the same width constraint to your new calculated number.
Your new calculated number is as follows:

```swift
let width = self.view.frame.width
var cellSize = CGFloat(width / 7).rounded() // var cellSize = floor(CGFloat(width / 7))
var newWidth = cellSize * 7
```
5. Set the width constraint outlet value to the newly calculated width.

**Comment by romaHerman** [comment] 2017-08-21 14:20
Thank you very much for quick reply 
I will recheck everything , try and let you know about results!

**Comment by patchthecode** [comment] 2017-08-23 06:45
Did not help?
If it is possible you can provide a sample app with that selection screen. I can code the solution.

**Comment by patchthecode** [comment] 2017-09-03 17:56
closing this issue.
If the problem is still existing for you, provide a small sample app. I'll code the fix.

**Closed** 2017-09-10 14:43 UTC

**Comment by meanreaksmey** [comment] 2018-08-11 06:36
![simulator screen shot - iphone 5s - 2018-08-11 at 13 35 43](https://user-images.githubusercontent.com/19529052/43988970-7e7cbeda-9d6b-11e8-8bf4-b7303957f164.png)

it still happened.

**Comment by patchthecode** [comment] 2018-08-11 13:55
@meanreaksmey 

what is the width of the calendarView when the app is run?

**Comment by meanreaksmey** [comment] 2018-08-12 05:27
@patchthecode I set constraint left and right to superview.

**Comment by patchthecode** [comment] 2018-08-12 06:10
@meanreaksmey yes.
therefore, what is the width of the calendaView when the app is run?

**Comment by meanreaksmey** [comment] 2018-08-12 06:14
@patchthecode I used calendarView.cellSize = 50  and calendarView width depend on screen because I use constraint left right

**Comment by patchthecode** [comment] 2018-08-12 08:30
Then this will not work.
You must know the width of your calendarView.
And the width when divided by 7 should not have a recurring point.

**Comment by meanreaksmey** [comment] 2018-08-12 08:32
After I divided by 7 I used it for size cell right!.

**Comment by patchthecode** [comment] 2018-08-13 18:18
i do not understand what you mean.
Let me make this most simple.

Please run your app. And put this code in your `viewDidLoad()` in the controller you have your calendar.
```swift
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            print(calendarView.frame.width)
        }
```

And please let me know the width of your calendar view please?

**Comment by patchthecode** [comment] 2018-08-13 18:18
@meanreaksmey 
i do not understand what you mean.
Let me make this most simple.

Please run your app. And put this code in your `viewDidLoad()` in the controller you have your calendar.
```swift
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            print(calendarView.frame.width)
        }
```

And let me know the width of your calendar view please?

**Comment by dbyst** [comment] 2018-09-06 09:50
Hi, I have this issue as well, but only on iPhone X

On iPhoneX screenWidth if 375.
Then I set widthConstraint for Calendar:
calendarWidthConstraint.constant = 52 * 7

And in result I have this:

<img width="335" alt="screen shot 2018-09-06 at 12 48 20 pm" src="https://user-images.githubusercontent.com/5080130/45149955-6d041500-b1d3-11e8-9651-2e9a911c1475.png">

**Comment by patchthecode** [comment] 2018-09-06 15:37
@dbyst 

<img width="784" alt="screen shot 2018-08-29 at 8 25 05 am" src="https://user-images.githubusercontent.com/2439146/44797956-3be96c00-ab65-11e8-84c2-b1556520f26b.png">

**Comment by dbyst** [comment] 2018-09-06 19:07
@patchthecode 
But in my example I have non-recurring decimal value

**Comment by patchthecode** [comment] 2018-09-06 20:00
@dbyst  When you pause your app on iphonex simulator, and you debug the view hierarchy, what is the width of the calendarView?
Tap on this to debug hierarchy
http://mobileapps23.apple.com:8081/testResults/98

**Comment by brandonaskea-mc** [comment] 2019-04-09 22:37
I have an idea. Give us the width of the cells that are being automatically created for us instead of "0". That'd help.

**Comment by patchthecode** [comment] 2019-04-09 23:03
@brandonaskea-mc but you are in control of the width of the cells via the width of the calendarView.width

**Comment by RoKang** [comment] 2019-05-29 06:18
I solved this problem in cell swift file.
After awakeFromNib() method called in cell, I add this code.

```
let width = UIScreen.main.bounds.width  
let selectedViewSide = CGFloat(width/7).rounded() - 0.05
widthConstraint.constant = selectedViewSide
heightConstraint.constant = selectedViewSide
```
widthConstraint and heightConstraint are connected to selectedView width and height constraint.

**Comment by neeraj92144** [comment] 2021-02-11 10:30
I AM HAVING THE SAME ISSUE 

<img width="405" alt="Screenshot 1942-11-22 at 3 44 40 PM" src="https://user-images.githubusercontent.com/26308047/107623931-1b072980-6c80-11eb-97b7-4fad24dd00a0.png">

Please check the code I prepare for you -> https://we.tl/t-e5AQOLP3oS

Please check thanks in advance.

**Comment by neeraj92144** [comment] 2021-02-11 10:32
I have already tried every possible ways that you have already mention in all the issue but unable to solve the issue, so prepare a code so that you have a look at it, what's the wrong thing making these white lines.

**Comment by patchthecode** [comment] 2021-02-11 18:26
@neeraj92144  what do you have as the width of your calendar?

**Comment by neeraj92144** [comment] 2021-02-12 01:14
let widtha = self.view.frame.width
 var cellSizwe = CGFloat(widtha / 7).rounded() // var cellSize = floor(CGFloat(width / 7))
 var newWidth = cellSizwe * 7
 calendarView.cellSize = cellSizwe
 calendarWidthConstraint.constant = newWidth

This is the code used for width as you mentioned in other issues.

As far as width is concern 

Screen width = > 414

Then performed -> (414 / 7).rounded() => 59

Then calendarView.cellSize = 59 

and calendarConstaint = 59 * 7

You can also check the code.

**Comment by patchthecode** [comment] 2021-02-12 03:11
as a test, can you set the calendarView.frame.width = 413 ?

**Comment by neeraj92144** [comment] 2021-02-12 05:59
let widtha = 413
            var cellSizwe = CGFloat(widtha / 7).rounded() // var cellSize = floor(CGFloat(width / 7))
            var newWidth = cellSizwe * 7
            calendarView.cellSize = cellSizwe
            calendarWidthConstraint.constant = newWidth


But same issue

**Comment by patchthecode** [comment] 2021-02-12 06:02
do not set the cell size.
Just set the calendar width.
Let the calendar calculate the cells' width for it self.
Let me know how it goes?

**Comment by neeraj92144** [comment] 2021-02-12 06:06
![Uploading Screenshot 1942-11-23 at 11.36.16 AM.png…]()

**Comment by neeraj92144** [comment] 2021-02-12 06:08
<img width="663" alt="Screenshot 1942-11-23 at 11 36 16 AM" src="https://user-images.githubusercontent.com/26308047/107735925-d6829900-6d26-11eb-9f83-d2f3d60d0863.png">

**Comment by neeraj92144** [comment] 2021-02-12 11:44
Please try with my setup code , simple one page view-controller where above calendar  issue is coming in.

**Comment by patchthecode** [comment] 2021-02-12 19:53
when i said to set the calendar with, i meant to set it the way its supposed to be done.
Set it with constraints.  I will take a look at my example over the weekend.
Or do you have sample app on github i can take a look at? 

Setting it up with the code you provided might not work on my end. I have seen this issue happen on someones app, but not on others, so i would prefer if i had an actual sample app to look at.

**Comment by neeraj92144** [comment] 2021-02-17 16:46
@patchthecode , please check code on GitHub itself , I tried everything from my end to resolve this issue, please have a look at asap.

https://github.com/neeraj92144/CallenderLineIssue

THANKS IN ADVANCE.

**Comment by patchthecode** [comment] 2021-02-18 07:03
what version xcode? and what iPhone are you using?
I ran your code and it looks ok.

iphone 11 pro 14.4
<img width="488" alt="Screen Shot 2021-02-18 at 2 02 15 AM" src="https://user-images.githubusercontent.com/2439146/108318205-6b551e80-718d-11eb-8daa-8b1533c25f8b.png">

**Comment by neeraj92144** [comment] 2021-02-18 10:22
I tried in two versions of Xcode first one is Xcode 11.3 and Now trying 11.5.

I tried on iPhone 7 with os version 13.6.1.

Also I tried using similar in simulator where code was running in 13.5 version.

**Comment by patchthecode** [comment] 2021-02-18 14:40
Hmm... i do not have lower versions of XCode to try it on.
I have one last queston to ask you on this --> is this also happening on the device? or is it happening on simulator only.

**Comment by neeraj92144** [comment] 2021-02-18 18:08
No same behaviour for the both.

**Comment by neeraj92144** [comment] 2021-02-18 18:26
Then how can you assist me, by accessing my Mac or something so that can see the real example in Xcode 11.5 or something.

**Comment by patchthecode** [comment] 2021-02-18 19:19
Ok. I got a lower version running on my system and I see the issue you mention.
I also see the solution.

Your constraints were not properly set.
I mentioned above That you solution should be [this](https://github.com/patchthecode/JTAppleCalendar/issues/538#issuecomment-419141101).

But you did not properly set your constraints to 413 (a number perfectly divisible by 7).
In fact, you still had your constraints in your Storyboard still being set to 414.

I have modified the storyboard to properly follow the advice given above.
[CallenderLineIssue-main.zip](https://github.com/patchthecode/JTAppleCalendar/files/6005287/CallenderLineIssue-main.zip)

**Comment by neeraj92144** [comment] 2021-02-19 07:20
Thanks a lot @patchthecode, It solved the line issue coming in.

**Comment by neeraj92144** [comment] 2021-02-20 00:15
@patchthecode , can you help me out , stuck badly.

**Comment by patchthecode** [comment] 2021-02-20 06:54
Can you do what I have done in the fixed example and pick a width that is divisible by 7?
The problem is not in the library, but in the way UIKit displays recurring decimal places.
Or you can do like what the others have done on this thread, and round your calculation to the nearest value that is divisible by 7.

The example I returned to you is fixed to 413. I only did this as an example so you can know that it does work if you pick widths divisible by 7. In your real code you should get the width of the device, and then pick a width that divides by 7.

Does this help?

**Comment by neeraj92144** [comment] 2021-02-20 10:15
Ok thanks, worked working fine in all the device after setting stack view heigh to dynamic. Now my issue is closed.
