### ISSUE TITLE
scrollingMode nonStopToSection(withResistance: CGFloat) skipping section

### ISSUE THREAD

**Issue by mgurreta** [patchthecode/JTAppleCalendar#629] opened 2017-11-18 04:22 UTC
1. PLEASE STATE THE VERSION NUMBER you are using.
    7.1.4
2. Are you using the latest version of JTAppleCalendar? 
    Yes
3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.
    I have a vertical scrolling calendar setup with nonStopToSection as scrollingMode. The issue I see is that not always stop on the next section (month), sometimes it skips a month and I have to try multiple times to get it stop, even give just the right amount of inertia to get it in the month I want to eventually stop.

I'm not able to repro on 7.0.6. I jumped from that version to the latest one in which I observe the issue.
https://github.com/patchthecode/JTAppleCalendar/compare/7.0.6...7.1.4

![vertical_scrolling_issue](https://user-images.githubusercontent.com/73706/32976927-51bcd68e-cbd7-11e7-8035-841a233ed7d7.gif)

**Comment by patchthecode** [comment] 2017-11-18 16:52
Will check it out this afternoon.

**Comment by mgurreta** [comment] 2017-11-19 21:39
Thanks @patchthecode 
```
.nonStopToSection(withResistance: 0)
```

**Comment by mgurreta** [comment] 2017-11-25 19:51
Hello @patchthecode, no clue right??

**Comment by patchthecode** [comment] 2017-11-25 20:40
Are you available now? Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

It could not reproduce it.

**Comment by patchthecode** [comment] 2017-11-25 20:44
Are you available now? Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

It could not reproduce it. 
Is it possible you can give me an empty sample project with the issue? 
I tried with my sample project, but every thing looks ok.

**Comment by mgurreta** [comment] 2017-11-25 21:01
@patchthecode can't join right now. But I'll put together an empty project for you. 
I'll do it this afternoon. In an hour or two

**Comment by mgurreta** [comment] 2017-11-25 22:46
@patchthecode here it is the sample app I created, the issue is reproducible there https://github.com/mgurreta/sample-JTAppleCalendar

**Comment by patchthecode** [comment] 2017-11-26 19:01
OK i think i was able to replicate it. 
To replicate it I had to scroll, and then while it is still scrolling i had to tap and hold with my finger, then scroll and release. (Im not sure if this is the same steps you used to experience it).

I know where to fix it. But I dont have the time now. I'll take a look at it probably on Monday.
The function in the library that handles scrolling action is `scrollViewWillEndDragging` located in the `UIScrollViewDelegates.swift` file.

**Comment by mgurreta** [comment] 2017-11-27 16:57
@patchthecode Nice. Yes, absolutely.. that is the way I repro it.

Nice that you already know where to start looking for this bug... Not sure if I will be able to provide a fix, I'm also without much time to spare.

Anyways, will see. Hopefully we can make it happen.

Thanks

**Comment by mgurreta** [comment] 2017-11-30 02:06
Hello @patchthecode !! did you get a chance to look into this issue?

Thanks in advance

**Comment by patchthecode** [comment] 2017-11-30 17:29
Sorry man. I got very tied up. You'll have an update on this after work today. deadlines.

**Comment by mgurreta** [comment] 2017-11-30 17:30
take it easy man!! :)

**Comment by patchthecode** [comment] 2017-12-02 17:15
ok checking this out today

**Comment by mgurreta** [comment] 2017-12-04 02:08
nice! any luck? @patchthecode

**Comment by patchthecode** [comment] 2017-12-04 02:51
Im in the process on re-coding the scrolling.
Its a stupid bug, based on one bad logic.
Rather than just putting in a patch, i decided to recode that function.

**Comment by mgurreta** [comment] 2017-12-04 02:54
hahaha you're awesome man! let me know when you think it is ready and I can give it a try...

**Comment by patchthecode** [comment] 2017-12-04 02:58
yea, i'll keep you posted.

**Comment by patchthecode** [comment] 2017-12-04 04:36
@mgurreta my code is very incomplete.
but can you let me know if master branch behaves like how you want?

**Comment by mgurreta** [comment] 2017-12-04 04:40
@patchthecode on it... give me 30mins to compile master and run some test

**Comment by patchthecode** [comment] 2017-12-04 04:54
I'm working on another screen, so if you need to message quickly, then send here so that i get a notification. -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by mgurreta** [comment] 2017-12-04 05:05
@patchthecode ok... so I build commit `4d5d9eb6bca96e9dc029171882060e8be946a373` using `carthage`,
I'm seeing debug print statements so we are good...
```
theTargetContentOffset = 2540.0
contentOffset = 2691.66666666667
theTargetContentOffset = 0.0
contentOffset = 2249.66666666667
theTargetContentOffset = 0.0
contentOffset = 115.666666666667
```

So... I'm not able to repro de reported bag anymore... but the scroll is not snapping to a section when I tap and release while scrolling. Instead, it completely stops the scroll leaving the calendar, sometimes, in the middle of 2 months. Which is not that bad, but I would expect that while releasing the tap the calendar will accommodate itself to the corresponding month.

i.e. If the user taps during scroll, the calendar stops, but when it releases the tap... if the calendar upper part of the calendar is showing between 1 to 15 days, the calendar will snap to the current month. But if the calendar instead stops between day 16 and up, then it will scroll and snap to the next month. Hopefully I made myself clear.

**Comment by mgurreta** [comment] 2017-12-05 02:53
@patchthecode I was thinking and actually avoiding the snapping when the user taps the screen it is cool... The thing is that with this scroll mode if you DON'T tap the screen, then when the inertia completely decelerate the frame finally snap to a section (month).. so we should make this behaviour consistent. Snap in all cases or avoid sapping at all.

.... from API perspective, like we discussed Yesterday, `nonStopToSection` I would expect the frame to snap, always, maybe add another `scrollingMode` ??

What do you think?

**Comment by patchthecode** [comment] 2017-12-05 03:27
After thinking about it
for consistency, i'll make it snap like it did before.
You're right when you say it may become too complex with `nonStopSnapToSection`. 

The library has been flexible enough to meet many people's needs upp till this point, so I think the behavoir should stay the same until someone has some use-case for another mode.

Thanks for the input dude.
Will get to work on this is a bit (maybe tomorrow). Hurrying up some code on the other project. I am free-er this week as my main project is semi-done.

**Comment by mgurreta** [comment] 2017-12-05 03:46
No man... Thanks youuu!!

Whatever your understanding of `nonStopToSection` dictates will be ok. The no snaping option was good, I was using the App with the latest code from master and feels good!! 

Your call! :)

please ping me if you need assistance, I'll try to connect to gitter.

**Comment by mgurreta** [comment] 2017-12-14 06:28
Hey @patchthecode long time no talk!! How are you doing? Hopefully everything is going well!

I pinging you to see if you had any chance to look into this bug any further?

Thanks man!

**Comment by patchthecode** [comment] 2017-12-15 12:37
I know its bad man. But its going slowly. Trying to make a hard deadline for monday coming. Thats why im answering simple questions for now. 
What I think i'll do is just make a patch on master branch for you only (instead of doing to major fix for all). That way you can continue with your work. After i am free-er, i can come back to it and clean up the code for everyone else.

**Comment by mgurreta** [comment] 2017-12-15 17:23
Hey man! I completely understand and you don't need to worry about.

I'm already working on the master branch, so you don't really need to do any patch, what it's already on the master is enough for now and don't block me. We can talk again next week.

Good luck with your project! hopefully, you can make it for Monday! 🏅

**Comment by mgurreta** [comment] 2018-01-02 02:42
Hello @patchthecode ! happy new year!!! 🍾 

Wondering if you had a chance to take a look at this issue?

Thanks!

**Comment by patchthecode** [comment] 2018-01-02 05:05
I had to release the new version to stop some other bugs.
So i did.
In regards to the scrolling issue, i have moved the fixing over to this branch -> https://github.com/patchthecode/JTAppleCalendar/tree/FixingScrolls

**Comment by patchthecode** [comment] 2018-01-02 05:09
This fix will come with a minor verstion bump.
One signature will be changed. (its supposed to be a major version change, but im hoping the developers will forgive me). I didnt want to do a major change for such a small change, even though it is breaking one code line.

**Comment by patchthecode** [comment] 2018-01-02 05:47
Completed scrollmodes are

- [ ] .nonStopToSection
- [ ] .none

**Comment by mgurreta** [comment] 2018-01-02 21:49
so you are thinking to avoid jumping to 7.2.0? (and hotfix this?)

I guess devs will understand a one-liner change... if they are in dev and not stick to a version.

**Comment by patchthecode** [comment] 2018-01-02 22:10
@mgurreta 
> I guess devs will understand a one-liner change

haha i hope the can forgive me..

**Comment by mgurreta** [comment] 2018-01-09 02:11
Hello @patchthecode ! how are you doing man??

just touching base on this issue.

thanks

**Comment by patchthecode** [comment] 2018-09-11 15:32
for now, im just doing small updates.
keep using the branch. I have not forgotten about it.

Its just that your update is very large. The updates i have  done on master branch thus far are just minor bug fixes. They will be ported over to that branch.
Eventually, when i get a good free week straight, i will just fix your once and for all.

Your fix will affect many users, so i've just been delaying. But you are not forgotten man.
Ideally, I do wish that someone who has more time than i do would just do a pull request.

**Comment by mgurreta** [comment] 2018-09-11 15:36
Thanks, my friend! Absolutely, I'm ok using the `FixingScrolls` branch. 

Unfortunately, I don't have to much time to work on it. Will see in the future...

In the meantime, I'll probably send you a PR with a merge brack from `master` into `FixingScrolls`.

Thanks man! 🚀

**Comment by patchthecode** [comment] 2019-04-27 13:38
I have fixed all the other bugs, and the library is now very stable.
I will start working on this in a bit.

**Comment by mgurreta** [comment] 2019-04-27 16:18
awesome @patchthecode!!

**Comment by patchthecode** [comment] 2019-05-05 16:32
reposting here.

Completed scrollmodes are the following. Others are being added as i compete them. Then will release.

- [ ] .nonStopToSection
- [ ] .none
- [x] .nonStopToCell
- [ ] .nonStopToCustomInterval
- [ ] .stopAtEachCustomInterval
- [ ] .stopAtEachSection
- [ ] .stopAtEachCalendarFrame

Restarted code.

**Comment by patchthecode** [comment] 2019-05-09 03:32
hey, i have finished the update.
Can you test to see if it fits your use cases?  If all is well i will merge with master branch.

To test follow [instructions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#common-questions-can-now-be-found-on-patchthecodecom). BUT change the branch name to **fixingScrolls2**. Remember to clear cache etc as said in the instructions.

Let me know of any new/old issues bugs etc.

**Comment by patchthecode** [comment] 2019-05-09 12:44
I couldnt wait :D

I merged with master branch.
closing this issue.
 But PLEASE do let me know if you see any bug .

**Closed by patchthecode** 2019-05-09 12:44 UTC
Labels: Already Fixed on Master Branch, bug

**Comment by mgurreta** [comment] 2019-05-09 17:56
Will do @patchthecode !

Thanks,
