### ISSUE TITLE
Can't reload dates from incomplete months

### ISSUE THREAD

**Issue by artemstepanenko** [patchthecode/JTAppleCalendar#601] opened 2017-10-25 10:03 UTC
Hello.

Thanks for the great work.

Version **7.1.1**.

I've encountered a problem: `JTAppleCalendarView` doesn't reload dates which don't belong to complete months.

**Example**: I show two months in the calendar: October and November, which means there're some dates from September (in the beginning of the October's page) and from December (in the end of the November's page). In this case, if I call 

```swift
func reloadDates(_ dates: [Date])
```
 for the September or December dates, it will trigger neither 
```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath)
``` 
nor 
```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell
```

Thanks,
Artem

**Comment by patchthecode** [comment] 2017-10-25 14:16
ok. I will look into this

**Comment by artemstepanenko** [comment] 2017-10-25 14:41
Thanks.

**Comment by patchthecode** [comment] 2017-11-02 02:43
i finally have time to look into this. 
Iv'e been trying, but all seems to be working well on my end no matter what i test.
Do you have a sample project that reproduces this? You can drop the zip file in this chat box. Just delete the build folder before zipping so it wont be too large.

**Comment by patchthecode** [comment] 2017-11-03 02:56
Or can you show me the library related code for the `cellForItem` function?

**Comment by patchthecode** [comment] 2017-11-10 15:32
closing this until user responds. I believe the issue might lie in the implementation of willDisplay and cellForItem.

**Closed by patchthecode** 2017-11-10 15:32 UTC
Labels: Awaiting User Input
