### ISSUE TITLE
Fatal error: Index out of range

### ISSUE THREAD

**Issue by mourgias** [patchthecode/JTAppleCalendar#1164] opened 2019-10-22 13:25 UTC
I face a problem on my debug console , anyone can figure out what is going on..??

When i am going to pick a date , i take an error Index out of range 

<img width="966" alt="Στιγμιότυπο 2019-10-22, 15 34 14" src="https://user-images.githubusercontent.com/49849043/67290114-55c3dc00-f4e8-11e9-8bea-38044d8ec519.png">

This problem i found it  on this page

![Στιγμιότυπο 2019-10-22, 16 26 52](https://user-images.githubusercontent.com/49849043/67290543-eb5f6b80-f4e8-11e9-9b83-560e813cea83.png)

**Comment by patchthecode** [comment] 2019-10-22 15:35
I just downloaded the example code and it works.
What are the steps to reproduce the error you are seeing?

**Comment by mourgias** [comment] 2019-10-23 10:07
when i am pick  a date, then unselect the specific date and after pick a previous date, then the app its crash 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49849043/67381715-0d162c80-f595-11e9-8549-48f47ddf0d34.gif)


iOS 13 - Xcode 11

**Comment by Abruuham** [comment] 2019-11-21 07:28
> when i am pick a date, then unselect the specific date and after pick a previous date, then the app its crash
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49849043/67381715-0d162c80-f595-11e9-8549-48f47ddf0d34.gif)
> 
> iOS 13 - Xcode 11

**I am using version 8.0.**

I was having the same issue today when trying to deselect the date that is already selected like you're showing. I was trying out different things and the only thing I could think of to somewhat remedy this was to add "|| !twoDatesAlreadySelected && cellState.selectionType != .programatic " to the shouldDeselectDate function: 

`func calendar(_ calendar: JTACMonthView, shouldDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) -> Bool {
        if twoDatesAlreadySelected && cellState.selectionType != .programatic || !twoDatesAlreadySelected && cellState.selectionType != .programatic {
            firstDate = nil
            calendarView.deselectAllDates()
            return false
        }
        return true
    }`

This however, has issues when selecting inDates/outDates so I have to remove user interaction on in/outDates. In the meantime this is the solution that I will be using in order for my app to not crash, hope it helps (:

**Comment by PNepikov** [comment] 2020-02-07 10:50
i did a different way
    func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
        if !self.calendarView.selectedDates.isEmpty {
            if twoDatesAlreadySelected && cellState.selectionType != .programatic || firstDate != nil && date < calendarView.selectedDates[0] {
                firstDate = nil
                let retval = !calendarView.selectedDates.contains(date)
                calendarView.deselectAllDates()
                return retval
            }
        }
        return true
    }

**Comment by alexvaiman** [comment] 2020-05-17 02:10
the fixes here are wrong - here is the correct fix.
```

  func calendar(_ calendar: JTACMonthView, shouldSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) -> Bool {
        
        if calendar.selectedDates.isEmpty {
            firstDate = nil
            return true
        }
        
        if twoDatesAlreadySelected && cellState.selectionType != .programatic || firstDate != nil && date < self.selectedDates[0] {
            firstDate = nil
            let retval = !self.selectedDates.contains(date)
            self.deselectAllDates()
            return retval
        }
        
        return true
    }
```

**Comment by patchthecode** [comment] 2020-05-17 11:16
The problem with this is that its not a bug in the library.
It is a bug in my example app.
I will close this issue.

**Closed by patchthecode** 2020-05-17 11:16 UTC

**Comment by alexvaiman** [comment] 2020-05-17 11:29
״The problem with this is that its not a bug in the library.
It is a bug in my example app.
I will close this issue.״ 
how about fixing the example? it will help others.

**Comment by patchthecode** [comment] 2020-05-17 11:38
I am sorry, but I do not have the time to do that.
The examples are not meant to be production code. It is to give developers an idea on how to solve.

This bug in particular, is because I didnt check for nil.
It almost like using force unwrap in production.  

if i fixed all the non-production errors in all my examples this will take me too much time.
So i would say this ->
Because this is a open source project, others can do the fix for me and push a fix. I will merge it.
I need all the help i can get, because I do not have much time anymore.

**Comment by alexvaiman** [comment] 2020-05-17 11:54
"This bug in particular, is because I didnt check for nil.
It almost like using force unwrap in production." - if you just check for nil, in some cases it will just hide the crash, the bug will still be there. (and will be harder to trace)
I am now using this grate lib in my project - if I shell find some useful fixes, production or not, I will push my code for review. 
p.s*
thanks for the grate lib.

**Comment by patchthecode** [comment] 2020-05-17 14:57
@alexvaiman 
thank you. I appreciate it.
