### ISSUE TITLE
Repeated week between two months with one row calendar

### ISSUE THREAD

**Issue by allemattio** [patchthecode/JTAppleCalendar#143] opened 2016-09-16 14:25 UTC
Hi @patchthecode 
I'm using your calendar in one row mode to have a week view.
I have a strange behaviour and I don't know if it's a bug or a misconfiguration problem.
Here's the thing, suppose that I'm in this situation, with a week between two months:
![img_0068](https://cloud.githubusercontent.com/assets/2228264/18588870/89c19678-7c28-11e6-924d-93e70fcd64ae.PNG)

If I scroll left, I would like to see the week from august 22nd to august 28th, but Instead I find another time this:
![img_0069](https://cloud.githubusercontent.com/assets/2228264/18588906/a98d4740-7c28-11e6-82eb-a258f88f6121.PNG)

And then, if I scroll again left I find this
![img_0070](https://cloud.githubusercontent.com/assets/2228264/18588917/b318c410-7c28-11e6-8c01-ae52e31ff358.PNG)

And scrolling again to the left I finally find the week from august 22nd to august 28th
I use dark gray in the day names for current month names and light gray for other months' day.
It's like there is an extra and useless week between two months.
This happens every time when I'm scrolling from a month to another. 

Here is the initialization code:
```swift
calendarView.dataSource = self
calendarView.delegate = self
calendarView.registerCellViewXib(fileName: cellXibName)
calendarView.cellInset = CGPoint(x: 0, y: 0)
calendarView.firstDayOfWeek = .Monday
calendarView.reloadData()
calendarView.selectDates([NSDate()])
calendarView.scrollToDate(NSDate(), triggerScrollToDateDelegate: false, animateScroll: false, preferredScrollPosition: .None, completionHandler: nil)
```

and here is the configureCalendar Method from the delegate

```swift
func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar) {
    var numberOfRows = 6
    if let calendarView = calendar as? AddictionJTAppleCalendarView{
        numberOfRows = calendarView.configuredNumberOfRows
    }
    let aCalendar = NSCalendar.currentCalendar()
    return (startDate: CalendarDateManager.sharedInstance.calendarStartDate, endDate: CalendarDateManager.sharedInstance.calendarEndDate, numberOfRows: numberOfRows, calendar: aCalendar)
}
```

Am I doing something wrong or is a bug?
Thanks in advance, and CONGRATULATIONS, this is by far the best calendar plugin, thank you so much for having developed it!!!!

**Comment by patchthecode** [comment] 2016-09-16 16:06
Its not a bug. What you are seeing is what every one else is asking for in singlerow mode --> The ability to remove in-dates and out-dates.

If you notice, in 6-row mode, you will see grayed out dates represesting in-dates/out-dates of the previous month and following month. 

<img width="373" alt="screen shot 2016-09-07 at 3 17 33 pm" src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png">

This works well for 6-row mode, but sucks for single row mode. I am working on an upgrade so that you can enable/disable this. I have the explanation here -> https://github.com/patchthecode/JTAppleCalendar/issues/129

currently the code is 90% complete. Unfortunately, I am making the upgrade for this in swift3 first. Afterwards I will support swift2.

**Comment by allemattio** [comment] 2016-09-16 16:13
Ok, I got the point. Thanks so much.
So I can try to use the DynamicGeneration branch or is it the same as master's situation?

**Comment by patchthecode** [comment] 2016-09-16 16:16
In Dynamic generation, thats where i am working on the code. You can test it out there.
However, some of the functionality is broken as I am still working on it. And I have a bunch of code to commit right now (which i still have locally). Working on the code still :)

**Comment by patchthecode** [comment] 2016-09-16 16:17
Keep in mind, the code will be in swift3

**Comment by allemattio** [comment] 2016-09-16 16:23
Ok thanks.
Another small question that I can't find in the docs.
Is possible to make the didScrollToDateSegmentStartingWithdate delegate method include the indates and outdates as the border of the segment, via a configuration parameter?
As an example, in the screenshot you posted the delegate would pass Feb 1st as start date and Feb 29th as end date, is possible to make it pass Jan 31St and Mar 12th?
I would also need this for my week view cal. :-)
Thanks a lot in advance

**Comment by patchthecode** [comment] 2016-09-16 18:46
hmm. That is a good idea. I will include it a an enhancement

**Comment by patchthecode** [comment] 2016-09-19 16:16
@allemattio by the way, could you let me know the reason for this upgrade?
I just need to know what the function does not already provide, so that I can make the best possible update.

**Comment by patchthecode** [comment] 2016-09-19 16:19
Also, this is now fixed on master branch. Testing is still in progress.

**Closed by patchthecode** 2016-09-19 16:19 UTC
Labels: Already Fixed on Master Branch, duplicate

**Comment by allemattio** [comment] 2016-09-19 16:22
@patchthecode I need that because I have to put under the week calendar a grid with the events for the week, just like the iphone landscape calendar.
So to query for the events I always need to have the borders of the visualized segment.

Thank you so much, what is fixed? the duplicated week or the part about the segment limits?

**Comment by patchthecode** [comment] 2016-09-19 16:28
What was fixed was the original issue. The in-dates/out-dates feature.

Ok one thing, concerning, the new enhance you want, will it still be necessary since you might be removing the in-dates/out-dates for the single row calendar?

**Comment by allemattio** [comment] 2016-09-19 16:35
@patchthecode I think that now that won't be necessary.
Since I will have no outdates, the segment should be always of 7 days.
Thank you so much, really.

**Comment by allemattio** [comment] 2016-09-19 16:54
@patchthecode just a question. This is fixed for Swift 2.2 and will be pushed to master, right?

**Comment by patchthecode** [comment] 2016-09-19 17:40
Hmm... Its hard for me to both maintain swift3 and swift 2.2..

..... The people here have already  requested a swift 2.3 branch, but my work place have already migrated to swift3. As I have mentioned to them in this issue -> https://github.com/patchthecode/JTAppleCalendar/issues/144 , someone will have to  create a branch called `Swift2.3` and maintain it as it is difficult for me to maintain so many versions.

Will your project be in swfit 2.3/2.2?

**Comment by allemattio** [comment] 2016-09-19 18:18
My project is in swift 2.2, sadly I don't think I'll have time to migrate it. I will try only if I can't workaround this issue

**Comment by patchthecode** [comment] 2016-09-19 19:57
Hmm. Well just so you know. Migrating is easy with XCode 8. It pretty much almost does every thing for you. But yea, some people will have to create a separate branch as it is a bit much for my plate.

**Comment by allemattio** [comment] 2016-09-19 20:29
On which branch and for which version have you fixed this Issue? 3 or 2.3?it's Also easy to migrate from 2.2 to 3 or only from 2.2 to 2.3?

**Comment by patchthecode** [comment] 2016-09-19 22:54
the branch i am making all the changes on is call `DynamicGeneration`
And I jumped straight from 2.1 to 3.
Most of the changes I had to make was done by XCode.
What you can do is save the old XCode copy, Download the new one, and try it.

**Comment by allemattio** [comment] 2016-09-20 07:57
I'm trying to bring the changes for the indate/outdate to the 2.2 branch, is it difficult? 
I'm trying to find out the part of code that generates the cells, also by following the `DynamicGeneration` branch code, but I still can't find it.
If it not take too much time to you, can you give me some advice about where I can find that code so I can modify it to exclude/include indates/outdates?

**Comment by allemattio** [comment] 2016-09-20 14:39
@patchthecode I tried converting the project to swift 3 to give a try to the code on the DynamicGeneration branch.
It was hard to migrate but I kind of made it, sweating a lot! :-)

Now, I saw the methods to generate indates outdates as said in [this issue](https://github.com/patchthecode/JTAppleCalendar/issues/129), but I think I have the same problem reported by the other user @mazurio , when scrolling right it have a strange behaviour between segments.
I set false to generate indates and .off to outdates
Using your screenshots I would expect this, suppose I start from this week:
![start](https://cloud.githubusercontent.com/assets/2228264/18674680/5537f12e-7f50-11e6-9424-bc09c0dc72d5.png)
then if I scroll to the right I expect to find this:
![right](https://cloud.githubusercontent.com/assets/2228264/18674691/5e95b6fc-7f50-11e6-8d9b-16241b5fd750.png)
 So I would like to have the segment of the same size, but with days from both months.
Then scrolling right again I would like to find the week from 13 to 19, and so on

Is this a bug or a misconfiguration caused by an error on my side?

**Comment by allemattio** [comment] 2016-09-20 15:33
@patchthecode  I migrated my code to swift 3 to try the DynamicGeneration branch, I managed to remove indates by setting false in the delegate, and removed the outdates by setting .off.

Now, 
In the month view of my app, which is a calendar configured with 6 rows, I have a small problem in the didScrollToDateSegmentStartingWithdate method, it returns me always the previous month.

In the week view, where I have another calendar configured with 1 row I have this problem, it's like that a day "disappears" now and then, look at these screenshots:

![img_0073](https://cloud.githubusercontent.com/assets/2228264/18677018/d56a0cc2-7f57-11e6-9cb3-cd9439ed8972.PNG)

Now if I scroll to the right I see:

![img_0074](https://cloud.githubusercontent.com/assets/2228264/18677030/dd7bc676-7f57-11e6-90d9-e65d8fc208f3.PNG)

To the right again:
![img_0076](https://cloud.githubusercontent.com/assets/2228264/18677059/eb35b92a-7f57-11e6-9f9a-c74fe3f638ac.PNG)


Another example, starting from:
![img_0077](https://cloud.githubusercontent.com/assets/2228264/18677148/2335df44-7f58-11e6-9b5c-586906989d0b.PNG)

and scrolling to the left I see:
![img_0079](https://cloud.githubusercontent.com/assets/2228264/18677152/28e1ab26-7f58-11e6-9e49-3efe4fbbc210.PNG)

Now and then a day disappears, and the weeks get misaligned.
I'm sorry, it' not easy to explain my problem. It's a bug or a configuration problem?

**Comment by patchthecode** [comment] 2016-09-20 16:08
Its a work in progress.
Thats why, it is not on the main branch yet.
I'm still working on it. Many little bugs here and there.
I should be finished soon though (if my real work doesnt bog me down with work. Since this is my side project)

**Comment by patchthecode** [comment] 2016-09-20 16:14
1st Day of week is not respected yet, because I have not completed the code there. It originally operated from the fact there is a defined 6x7 grid. But now, setting in-dates/out-dates on/off breaks this rule. So I have to code for that.

**Comment by allemattio** [comment] 2016-09-20 17:16
@patchthecode thanks, I won't bother you, I'll just peacefully wait for the fixes! :-)
Thanks again for your amazing work

**Comment by patchthecode** [comment] 2016-09-21 04:01
No worries. In fact, i actually need you guys to tell me where the bugs are.
I just made a push to `DynamicGeneration`. Can you let me know what else you find?

**Comment by allemattio** [comment] 2016-09-21 06:38
@patchthecode I will try it today and I will let you know. Just for knowledge, the branch `Swift3` can be considered stable?

**Comment by allemattio** [comment] 2016-09-21 06:53
@patchthecode I got this error:
cellCacheSection does not exist.
There was an error in this code section. Please contact the developer on GitHub
assertion failed: file <my project>/Pods/JTAppleCalendar/Sources/JTAppleCalendarView.swift, line 334

**Comment by patchthecode** [comment] 2016-09-21 08:34
ok.

1. Firs thing, why do you have to put it int he viewDidAppear method? What is the wrong with viewDidLoad?

2. Can you show me you `configureCalendar` function? In order to recreate your issue I have to know what type of calendar you have. **All** the settings for it. Eg. horizontal? vertical? Number of rows? etc etc etc. Just paste the `configureCalendar` function code

**Comment by patchthecode** [comment] 2016-09-21 08:36
Also, let me see your viewDidLoad code for the calendar please

**Comment by allemattio** [comment] 2016-09-21 08:38
@patchthecode  If I leave it in the viewDidLoad, it is not rendered correctly, it's not visible.

here is the function:


`    
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {

        let aCalendar = Foundation.Calendar.current
        if calendar == self.weekCalendarView {
            return ConfigurationParameters(startDate: CalendarDateManager.sharedInstance.calendarStartDate,
                                           endDate: CalendarDateManager.sharedInstance.calendarEndDate,
                                           numberOfRows: 1,
                                           calendar: aCalendar,
                                           generateInDates: false,
                                           generateOutDates: .off,
                                           firstDayOfWeek: .monday)
        }
        else {
            return ConfigurationParameters(startDate: CalendarDateManager.sharedInstance.calendarStartDate,
                                           endDate: CalendarDateManager.sharedInstance.calendarEndDate,
                                           numberOfRows: 6,
                                           calendar: aCalendar,
                                           generateInDates: true,
                                           generateOutDates: .tillEndOfGrid,
                                           firstDayOfWeek: .monday)
        }
    }
`

**Comment by patchthecode** [comment] 2016-09-21 08:38
Ok. Do you have headers registered?

**Comment by patchthecode** [comment] 2016-09-21 08:39
chat here is slow.. Mind joining me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by allemattio** [comment] 2016-09-21 08:39
no, no headers.


here is the code called in the viewDidLoad


` 
        calendarView.addWarrantBorder()

        calendarView.dataSource = self
        calendarView.delegate = self
        calendarView.registerCellViewXib(fileName: cellXibName)
        calendarView.cellInset = CGPoint(x: 0, y: 0)
        calendarView.reloadData()
        calendarView.selectDates([Date()])
        calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: false, animateScroll: false, preferredScrollPosition: .none, completionHandler: nil)`

**Comment by allemattio** [comment] 2016-09-21 08:41
sure, joining the chat

**Comment by allemattio** [comment] 2016-09-21 09:50
@patchthecode find this problem on the DynamicGeneration branch, with a calendar with 6 rows and this config:

```
CalendarDateManager.sharedInstance.calendarStartDate,
                                           endDate: CalendarDateManager.sharedInstance.calendarEndDate,
                                           numberOfRows: 6,
                                           calendar: aCalendar,
                                           generateInDates: true,
                                           generateOutDates: .tillEndOfGrid,
                                           firstDayOfWeek: .monday)
```

The calendar has only 5 rows
![img_0080](https://cloud.githubusercontent.com/assets/2228264/18706236/7ae3719a-7ff1-11e6-8e3b-08eed34826df.PNG)

**Comment by patchthecode** [comment] 2016-09-21 16:30
Ok one thing, when posting your code here, can you remove lines like this? 
```
CalendarDateManager.sharedInstance.calendarStartDate
```

Can you replace it with the actual date string? I do not know what is the start date and endDates with those lines in there

**Comment by patchthecode** [comment] 2016-09-24 02:03
Ok. Made some changes. 
Try the latest sample app

**Comment by allemattio** [comment] 2016-09-26 14:16
I tried to use the DynamicGeneration branch in my app but freezes on launch. 
The example seems instead correct, apart from the scroll that is not paginated.

**Comment by patchthecode** [comment] 2016-09-26 14:27
The example scroll is set in the `viewDidLoad` function where I have the code

```
calendarView.scrollingMode = .nonStopToCell(withResistance: 0.75)
```
delete that line of code to have you scroll paginated.

You say it freezes your app.
Does it crash or anything?

**Comment by patchthecode** [comment] 2016-09-26 14:27
Btw, if chat is too slow, you can join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment] 2016-09-26 14:35
Also, the names of some functions were changed to make it more standard. I think your app is freezing because since the function names have changed, the library is trying to call functions that does not exist in your app because the delegate function names are now different?
