### ISSUE TITLE
JTAppleCalendarCell not showing all views inside it

### ISSUE THREAD

**Issue by ggirotto** [patchthecode/JTAppleCalendar#398] opened 2017-04-29 22:38 UTC
Version : 7.0.1

My problem is that 2 of 4 Views that im putting inside the UICollectionViewCell are not appearing for some reason. It looks like the cell it's limiting the number of elements inside it. All the 4 Views are identical, but 2 of them are not appearing. I searched about it but didn't found anything that could help me. I tried even to overlay them, but even when i do it, they do not appear, Its just like the cell is bypassing them. Some pictures that may help to illustrate the situation

![image](https://cloud.githubusercontent.com/assets/11745745/25559554/3b9c51e4-2d13-11e7-8f77-76855c137500.png)
![image](https://cloud.githubusercontent.com/assets/11745745/25559558/44b3184e-2d13-11e7-8fe8-fb58b2dc8c77.png)
![image](https://cloud.githubusercontent.com/assets/11745745/25559560/4a07ee82-2d13-11e7-8383-d3ab8a3be548.png)

The pictures show that he's just showing the views from the middle. I thought that the problem could be space, however, as I sad, I tried to overlay them to see what happen and nothing. I've already made basic setup, as connecting them to my custom class. My custom class code:
`import UIKit
import JTAppleCalendar

class CustomCell: JTAppleCell {

@IBOutlet weak var dateLabel : UILabel!
@IBOutlet weak var selectedView : UIView!
public var cellDate : Date?

@IBOutlet weak var firstTrainingCircle: UIView!
@IBOutlet weak var secondTrainingCell: UIView!
@IBOutlet weak var thirdTrainingCell: UIView!
@IBOutlet weak var fourthTrainingCell: UIView!

}`

The day label, the View that display when the cell is selected and the middle Views are appearing as they should, so, why the green and red views are ignored? I really have no idea why, excuse me if It's a dumb question, but since Im trying to solve It since yesterday and could get It I ask to you guys.

**Comment by patchthecode** [comment] 2017-04-30 04:04
By any chance those 2 end views (left and right) are accidentally inside of the `Red` view? 

If youre free, you can join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by ggirotto** [comment] 2017-04-30 04:31
No, i already verified it

**Comment by patchthecode** [comment] 2017-04-30 04:33
Any chance you can send or show a sample app?
If not, i can talk more here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by ggirotto** [comment] 2017-04-30 04:40
Yes, i can. Actually im leaving at the moment. If you still on tomorrow i can chat with you. Tomorrow i will reproduce the error in a simple app and send it to you. Thank you for the help ;)

**Comment by patchthecode** [comment] 2017-04-30 04:49
Awesome. Will await this.

**Comment by ggirotto** [comment] 2017-04-30 13:18
Thank you for waiting. Im sending a simple app reproducing my problem.
[ReproduceError.zip](https://github.com/patchthecode/JTAppleCalendar/files/966745/ReproduceError.zip)

**Comment by patchthecode** [comment] 2017-04-30 14:21
Looks ugly, but i thin the problem was in your constraints.

[ReproduceError.zip](https://github.com/patchthecode/JTAppleCalendar/files/966778/ReproduceError.zip)

**Comment by patchthecode** [comment] 2017-04-30 16:01
closing issue now.
If you got anymore questions. just ask away.
cheers 🍻

**Closed by patchthecode** 2017-04-30 16:01 UTC
Labels: Awaiting User Input

**Comment by ggirotto** [comment] 2017-04-30 16:12
Worked perfectly ;). Thank you
