### ISSUE TITLE
The first week of 2018 year bug

### ISSUE THREAD

**Issue by serfeo** [patchthecode/JTAppleCalendar#675] opened 2018-01-06 12:52 UTC
Hi, it looks like the first week of this year for calendar week mode works incorrect.
I'm using JTAppleCalendar (7.1.5).
I'm using this parameters to initialize calendar:
`let startWeek = Date().startOfWeek( .monday )`
`let startDate = startWeek.addingTimeInterval( -5 * 7 * 24 * 60 * 60 )`
`let endDate = startWeek.addingTimeInterval( 5 * 7 * 24 * 60 * 60 )`
`let parameters = ConfigurationParameters(
            startDate: startDate,
            endDate: endDate,
            numberOfRows: 1,
            firstDayOfWeek: .monday )`
In the viewDidLoad function I'm scrolling calendar to the current date:
`weekCalendarView.scrollToDate( selectedDate, animateScroll: false )`
So after application started I get this week calendar view
![simulator screen shot - iphone 8 plus - 2018-01-06 at 15 35 18](https://user-images.githubusercontent.com/4578898/34639793-b9fe3ba6-f2f7-11e7-95e2-115cdd475f0a.png)
When I scroll this calendar view to the left a bit I get this week calendar view
![simulator screen shot - iphone 8 plus - 2018-01-06 at 15 36 29](https://user-images.githubusercontent.com/4578898/34639797-d5a925dc-f2f7-11e7-898b-1c46b680d028.png)
As you can see after the 7th of January there is the the 1st of January.
I'm not sure is it bug, so I would be grateful, if you check it. 
Thanks.

**Comment by patchthecode** [comment] 2018-01-06 16:20
not a bug.
here is the configuration for a 1 week calendar https://github.com/patchthecode/JTAppleCalendar/issues/581

Closing this issue.
If this does not fix it, then let me know. 👍

**Closed** 2018-01-06 16:20 UTC
