### ISSUE TITLE
Missing date numbers when hiding in dates

### ISSUE THREAD

**Issue by fweathers** [patchthecode/JTAppleCalendar#497] opened 2017-07-24 19:12 UTC
Is there a method/func that allows for the .inMonth dates that are in the past to have a different colour than the present and future dates?

**Comment by fweathers** [comment] 2017-07-24 20:08
i just made the font the same colour as the background and then disabled the in dates.

**Comment by patchthecode** [comment] 2017-07-24 21:57
hmm. got a bit confused by the title vs the question.

> Missing date numbers when hiding in dates

Is there a bug you are experiencing? or do you just want to have inDates/outDates to become invisible?

If you just want them to become invisible, then all you will have to do is just set their `isHidden` property to be = `true`.  Let me know.

**Comment by fweathers** [comment] 2017-07-25 11:59
Sorry, I originally found a bug when setting inDates and outDates equal to off. When I would hide them, I would end up with months missing dates once i started to scroll. Eventually, I created a mini hack and just changed the text colour to blend in with the background and disabled the user interaction on them. I then changed the content of the question to ask if there was a way to change the dates text colour in the current month to light grey for the dates that have already passed, i.e. today's July 25 so the dates July 1-23 would have light grey text and then the current and futures dates will have black text.
![screen shot 2017-07-24 at 3 12 32 pm](https://user-images.githubusercontent.com/12614576/28571067-1cc97e82-710f-11e7-8898-73d2aa98b7d8.png)

**Comment by patchthecode** [comment] 2017-07-25 13:28
ok. i got you.
One thing though, if thats a bug, then thats really bad.
But i want to hope that many it was a mistake and not a bug, because i've tested this for over a year haha.

When you hid the dates by doing `cell.isHidden = true`  did you ever unhide them by setting `cell.ishidden = false` ?
I am guessing this was the problem.

**Comment by fweathers** [comment] 2017-07-25 14:11
That works :-) (adding cell.isHidden = false fixes this issue). I did have another question in regards to the current date being highlighted. I followed the video tutorial, but once i select off of the current date, the highlighting is no longer there. is there a way to keep the current date highlighted (light grey) even after selecting another date?

**Comment by patchthecode** [comment] 2017-07-25 15:13
The way provided in the video is only an example to show you how you can customize the main cell. But in regards to how to keep selections and designs etc, this is all specific to the developer and is not library specific questions. This is more a question that relates to a specific implementation.

But if you need help, here is how i would do it. In the `cellForItem` function, simply do:
```swift
if cellState.date == todaysDate {
   myCustomCell.backgroundColor = UIColor.red
else {
   myCustomCell.backgroundColor = nil
}
```

But i do not know your code So this is a start. 👍 
Closing this issue now and original question was answered. :)
Cheers.

**Closed by patchthecode** 2017-07-25 15:13 UTC

**Comment by fweathers** [comment] 2017-07-25 17:44
thanks
