### ISSUE TITLE
didDeselectDate not called due to incorrect startOfMonth / endOfMonth caches

### ISSUE THREAD

**Issue by NSMyself** [patchthecode/JTAppleCalendar#651] opened 2017-12-06 15:14 UTC
1. I'm using version 7.1.4
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.4

Basically, I've got a cell that has a round layer (shown in orange in the GIF) that indicates if the corresponding day is selected or not and I noticed that when I picked two dates from the past month the `didSelectedDate` method wasn't called at all.

![agbmoia](https://user-images.githubusercontent.com/2439146/33669808-4f45dfba-da58-11e7-8e8b-374ae8747455.gif)

As you can see, whenever I select the 30th of November, the `didDeselectDate` method isn't called. I tried to force the calendar to deselect the cell by adding `calendar.deselectDates(from: oldDate)` but to no avail.

After investigating, I came to the conclusion that the issue lies in the fact that the `startOfMonthCache` & `endOfMonthCache` variables (used in the `pathsFromDates` method, in the InternalQueryFunctions.swift file) still contained old values - the start and end dates of December, the previous month, instead of the ones belonging to November.

As such, that particular method would return no path at all and the `deselect` method never gets called in the `deselect(dates: [Date] , triggerSelectionDelegate: Bool = true)` method further along the line.

**Comment by patchthecode** [comment] 2017-12-06 15:38
Have you correctly implemented the `willDisplayCell` as shown here? #553

**Comment by NSMyself** [comment] 2017-12-06 15:51
Nope, I had not. Thanks for the info but I'm afraid the issue is still occurring over here. 

Here's my implementation:

```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        guard let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: CalendarCellView.name, for: indexPath) as? CalendarCellView else { return JTAppleCell() }
        
        prettify(cell, using: date, state: cellState)
        return cell
    }
    
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        guard let cell = cell as? CalendarCellView else {
            return
        }
        
        prettify(cell, using: date, state: cellState)
    }
    
private func prettify(_ cell: CalendarCellView, using date: Date, state cellState: CellState) {
        cell.dayLabel.text = cellState.text
        cell.dayLabel.textColor = colorOf(selectedDate: date, currentDay: viewModel.selectedDate)
        
        // Checking if we need to show the same day indicator
        let sameDay = (Calendar.current.compare(date, to: viewModel.selectedDate, toGranularity: .day) == .orderedSame)
        cell.selectedView.isHidden = !sameDay
}
```

**Comment by patchthecode** [comment] 2017-12-06 15:56
Ok testing this now.

**Comment by patchthecode** [comment] 2017-12-06 15:57
Whats the start and end dates for you calendar?
Do you have vertical/horizontal?
Do you have singleSelect/ multiSelect?

**Comment by patchthecode** [comment] 2017-12-11 07:51
found the reason why.
Will work on a fix.

**Comment by patchthecode** [comment] 2017-12-29 17:07
hi
in the `UserInteractionFunctions.swift` file, you'll see this code located in the following funciton

```swift
public func selectDates(_ dates: [Date], triggerSelectionDelegate: Bool = true, keepSelectionIfMultiSelectionAllowed: Bool = false) {
...
...
   if !(firstDayOfDate >= startOfMonthCache! && firstDayOfDate <= endOfMonthCache!) { continue }
...
...
}

```
Can you delete it and tell me if your problem is fixed? If it is, i will merge the fix into master branch.

**Comment by patchthecode** [comment] 2017-12-29 17:14
The problem was that the date you are trying to select is not contained in your calendar's range. It is outside of your startDate and endDate. But you still allowed the user to select it.

**Comment by reden87** [comment] 2017-12-31 00:04
Hi @patchthecode!

I have a similar problem here and I can tell you how to reproduce it (the previous fix is not fixing the problem).

I'm trying to achieve the following scenario:
* the start date is today
* the end date is 15th of January
* I use multi selection
* I don't want to allow select days before tomorrow and after 15th of January

I tried out the above scenario in the TestViewController.swift, here's my code:

```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        
        let startDate = Date() // changed this
        let endDate = formatter.date(from: "2018 01 15")! // changed this
        
        let parameters = ConfigurationParameters(startDate: startDate,endDate: endDate)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
        
        // added the code below
        formatter.dateFormat = "yyyy MM dd"
        let endDate = formatter.date(from: "2018 01 15")!
        
        if date < Date() || date > endDate {
            calendar.deselect(dates: [date])
        }
    }
```

As you can see I programmatically deselect the days I don't want to allow.

And here's what's happening in the app (after tapping the multiSelect button):

![simulator screen shot - iphone 6 - 2017-12-31 at 00 54 26](https://user-images.githubusercontent.com/869119/34458095-a5b21d98-edc5-11e7-9295-30c9dc97a6ba.png)

![simulator screen shot - iphone 6 - 2017-12-31 at 00 54 28](https://user-images.githubusercontent.com/869119/34458097-aa0af8ec-edc5-11e7-9e59-c95966baed22.png)

The good thing is:
* I cannot select days between 1st of December and 31th of December
* I cannot select days between 16th of January and 31th of January

The bad thing is:
* I can select days in November and in February

Looks like the bug is related to days which are not in the target month but visible in the calendar either in the beginning or at the end.

**Comment by NSMyself** [comment] 2017-12-31 00:07
@patchthecode Yes, i want to select a date outside of startDate. 
Basically, the user can select any day at all. 

The only thing I have to show is that all the days from the current month are shown with a particular color, while days from past / future months are shown with a different color altogether.

**Comment by patchthecode** [comment] 2017-12-31 06:34
@reden87 Hi, if you do not want dates to be selected, then you should implement the this delegate function ->

**Comment by patchthecode** [comment] 2017-12-31 06:37
@NSMyself 

In the `UserInteractionFunctions.swift` file, you'll see this code located in the following funciton

```swift
public func selectDates(_ dates: [Date], triggerSelectionDelegate: Bool = true, keepSelectionIfMultiSelectionAllowed: Bool = false) {
...
...
   if !(firstDayOfDate >= startOfMonthCache! && firstDayOfDate <= endOfMonthCache!) { continue }
...
...
}

```
Can you delete that line of code and tell me if your problem is fixed? If it is, i will merge the fix into master branch.
Awaiting your response.

**Comment by reden87** [comment] 2017-12-31 10:20
@patchthecode whoo thanks that worked for me.

I propose to investigate the scenario I wrote tho because I believe that's a bug anyways.

**Comment by patchthecode** [comment] 2017-12-31 15:52
@reden87 the problem you mention is not resolved by commenting out this line of code?
If not, then i'll look into it some more.

```swift
   if !(firstDayOfDate >= startOfMonthCache! && firstDayOfDate <= endOfMonthCache!) { continue }
```

**Comment by reden87** [comment] 2017-12-31 16:32
@patchthecode it's not resolved when I comment that line out.

**Comment by patchthecode** [comment] 2017-12-31 16:44
@reden87 can you message me here?
https://gitter.im/patchthecode/JTAppleCalendar
messaging here is too slow

**Comment by patchthecode** [comment] 2017-12-31 17:03
@reden87 one thing.

Are you saying that the library should prevent selection of the November month and Feburary month? If this is what you are saying, then please know that I have intentionally allowed this.

In the past, This library disallowed the selection of those dates. And I had requests of people to allow it. Take for instance this developer -> @NSMyself 
He also wants those dates to be selected.

So to make every one happy, i allowed it. And i left it up to the developer to prevent selection by using the `shouldSelect` delegate function. Does this answer your question?

**Comment by patchthecode** [comment] 2017-12-31 18:41
@NSMyself if its possible, lets talk again -> https://gitter.im/patchthecode/JTAppleCalendar
I want to close up this issue together with other issues before Jan.

**Comment by ajandrade** [comment] 2018-01-18 09:27
@patchthecode I tried to comment the line you mentioned above but it didn't solve the problem as you can see below:

![bug](https://user-images.githubusercontent.com/25066243/35090479-aeb0c604-fc31-11e7-812d-a497d0af5f80.gif)

**Comment by NSMyself** [comment] 2018-01-18 10:03
Sorry @patchthecode, totally forgot about this. @ajandrade is now responsible for this feature and, as such, please talk with him regarding this issue.

Thank you once more for the amazing support, much appreciated.

**Comment by patchthecode** [comment] 2018-03-05 00:29
@ajandrade not sure if this is still an issue.

**Comment by ajandrade** [comment] 2018-03-06 16:46
yes, it is @patchthecode . I tried to do what you suggested above, by commenting some lines, but it didn't work as you can see in my last reply.

**Comment by patchthecode** [comment] 2018-03-06 16:51
@ajandrade ok. Do you still have a small sample app which can reproduce this?

**Comment by gaus55** [comment] 2018-03-27 20:04
@patchthecode I have created the Calendar but issue is I want complete calendar dates from beginning to end not want to pass as string and my current date should be my first screen. I also want to deselect the dates from current date to Future How can i do it?

**Comment by patchthecode** [comment] 2018-11-04 16:44
@gaus55 open a new issue for this.
Closing original as no response.

**Closed by patchthecode** 2018-11-04 16:44 UTC
Labels: Awaiting User Input
