### ISSUE TITLE
Memory spike when programmatically scroll calendar without animation

### ISSUE THREAD

**Issue by Sothyrith** [patchthecode/JTAppleCalendar#953] opened 2018-12-19 14:47 UTC
I'm using the latest version, 7.1.6.

I created a demo project that calls scrollToSegment(.next) in the didSelectDate delegate method and the memory would keep climbing by about 1MB for every new segment and would only drop after I scroll the calendar on the screen. I have also tried this with scrollToDate and it causes the same problem. There doesn't seem to be any issues when I enable scroll animation.

```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! CustomCell
        cell.label.text = cellState.text
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "customCell", for: indexPath) as! CustomCell
        cell.label.text = cellState.text
        
        return cell
    }
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        dateFormatter.dateFormat = "dd mm yyyy"
        let startDate = Date()
        let endDate = dateFormatter.date(from: "25 01 2025")
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate!)
        
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        //print(date.toFormat("MMMM dd yyyy"))
        //calendar.scrollToDate(date.dateAtStartOf(.month).dateAt(.nextMonth), animateScroll: false)
        calendar.scrollToSegment(.next, animateScroll: false)
    }
```

**Comment by Sothyrith** [comment] 2018-12-19 14:49
I don't know how helpful this screenshot will be, sorry if it's not lol
<img width="1101" alt="screen shot 2018-12-19 at 9 09 16 pm" src="https://user-images.githubusercontent.com/44455656/50227202-ce916d80-03d7-11e9-8886-9a64428eed9a.png">

**Comment by patchthecode** [comment] 2019-03-13 15:29
i guess some more investigation is needed here.
Under the hood for this library, i use UICollectionView code :/

I do not do anything fancy under the hood, so I am not sure as the cause.
Is this issue for device? or on simulator.

**Comment by patchthecode** [comment] 2019-03-13 15:37
closing this issue.
I did not notice this on latest build.
You can chip in your thoughts on this.

**Closed by patchthecode** 2019-03-13 15:37 UTC
