### ISSUE TITLE
Selecting Dates and scrolling to another calendar frame bugs

### ISSUE THREAD

**Issue by AdautoP** [patchthecode/JTAppleCalendar#1120] opened 2019-08-20 13:34 UTC
**(Required) Version Number:**
8.0.1

## Description
When
## Steps To Reproduce
1st: select a date on current month (specially if the date is an dayOut date)
2nd: scroll to another month ( with scrollingMode set to .stopAtEachCalendarFrame)
3rd: scroll back to the current month
## Expected Behavior
Usually it bugs, resulting in multiple days selected.
## Additional Context

I have the cellForRow set to always configure the cell based on the cellState, so it's probably not a reusable problem.

**Comment by patchthecode** [comment] 2019-08-20 22:26
Have you implemented both the `cellForItem` and the `willDisplayCell` function?
And if yes, can you paste their codes for me?

**Comment by AdautoP** [comment] 2019-08-20 22:30
**Yeah i have! That's the only line inside them:**
`cell.configureCell(cellState: cellState)`

**and inside the cell i have:**
`func configureCell(cellState: CellState) {
        label.text = cellState.text
        handleCellTextColor(cellState: cellState)
        handleCellSelected(cellState: cellState)
    }
    
    func handleCellTextColor(cellState: CellState) {
        if cellState.dateBelongsTo == .thisMonth {
            label.textColor = UIColor.black
        } else {
            label.textColor = UIColor.gray
        }
    }
    
    func handleCellSelected(cellState: CellState) {
        if cellState.isSelected {
            selectedView.isHidden = false
        }
        else {
            selectedView.isHidden = true
        }
        selectedView.layer.cornerRadius = selectedView.frame.size.width/2
    }`

**Comment by AdautoP** [comment] 2019-08-20 22:40
If it helps, tomorrow i can create a new project with only the JTACMonthView in it and leave it public so you can test it by yourself. I would do it today but i forgot my Macbook charger at work :/

**Comment by patchthecode** [comment] 2019-08-21 03:26
that would be a lot easier for me. thanks.
let me know once done.

**Comment by AdautoP** [comment] 2019-08-21 12:03
I've branched my existing project into a public repository, check [here](https://github.com/AdautoP/JTAppleCalendarExample.git).

In that, you will look for CalendarView, that is a view that contains the JTACMonthView and is its delegate.

**Comment by AdautoP** [comment] 2019-08-21 18:24
Hey, is there anyway I can use the method .scrollToDate(date:) without the animation?

**Comment by patchthecode** [comment] 2019-08-21 22:14
@AdautoP yes

CMD click into that function. It has MANY optional parameters.
On a future note, many of the functions of this library has optional parameters.
I'll look at you branch after work

**Comment by AdautoP** [comment] 2019-08-21 22:48
Oh, lol. I didn't even try to CMD click it. Totally my bad!

**Comment by patchthecode** [comment] 2019-08-22 10:38
hmm.. maybe something is missing in that project? when in run it, i see a blank red screen.

**Comment by AdautoP** [comment] 2019-08-22 10:52
Weird, I'll have a look right now and fix it.

**Comment by AdautoP** [comment] 2019-08-22 11:17
Should be fine now! [I'll leave the link here again](https://github.com/AdautoP/JTAppleCalendarExample)

**Comment by patchthecode** [comment] 2019-08-22 11:18
ok checking

**Comment by patchthecode** [comment] 2019-08-22 11:21
Is there any specific dates to select?
You mentioned outDates, but on your example outDate selection is disabled. So i am wondering if you were referring to something different?

**Comment by AdautoP** [comment] 2019-08-22 11:23
Any dates you select can bug, but specially outDates. Because of that, I disabled outDates selection so it wouldn't happen frequently. But you can enable it for testing.

**Comment by AdautoP** [comment] 2019-08-22 11:23
Just select a date, scroll to another month then come back, the cell will probably still be selected.

**Comment by patchthecode** [comment] 2019-08-22 11:24
thanks. checking

**Comment by patchthecode** [comment] 2019-08-22 11:27
Well, i have not tested to see the bug yet. But i just found a bug it the code that could cause it.

```swift
guard let cell = calendarView.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as? DayCell else { return }
        cell.configureCell(cellState: cellState)
```

In will display, never re-create a new cell in there. We do not do this for regular collectionViews, so we shouldnt do it here as well.  That code should be this

```swift
    func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        guard let cell = cell as? DayCell else { return }
        cell.configureCell(cellState: cellState)
    }
```

This also is the reason why your calendar scrolling was very lagged.

**Comment by patchthecode** [comment] 2019-08-22 11:29
let me know if the issue is resolved for you.

**Comment by AdautoP** [comment] 2019-08-22 11:30
Ok! I'll try. For the scrolling, I've disabled the animation, so it works as I want it to, but I'll fix it as you said and then feedback.

**Comment by patchthecode** [comment] 2019-08-22 11:32
When i say "scrolling", i mean regular scrolling.
Scrolling as in, simply taking your mouse and scrolling the calendar.
It was lagging badly. But once the code fix is done, it is smoother.

**Comment by AdautoP** [comment] 2019-08-22 11:33
Ok, I fixed the issue you said and kept clicking for the whole 2 minutes and no bug happened again. All my fault then! thank you! :D

**Comment by patchthecode** [comment] 2019-08-22 11:36
Youre welcome.
Closing this issue now

**Closed by patchthecode** 2019-08-22 11:36 UTC
