### ISSUE TITLE
Cell is nil in didSelectDate when selecting programically

### ISSUE THREAD

**Issue by fenuks** [patchthecode/JTAppleCalendar#942] opened 2018-11-26 17:10 UTC
Hello, using last version of the library, I stumbled upon issue with range selection. 

Bug can be reproduced with patch I attach below with following steps:
Stroll to November. Click on 26th, then click on 1st December on the same segment (without scrolling to December, that is), click once again on 1st December, and this time `didSelectDate` delegate method will be called with cell == nil.

[Patch](https://github.com/patchthecode/JTAppleCalendar/files/2616604/test.txt)

**Comment by patchthecode** [comment] 2018-11-26 22:15
The function name for the function is
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState)
```

As is seen on the function name, the cell is nillable.
It can be nil if the cell that you are selecting is not on the screen.
Closing this issue, let me know if you have other questions.

**Comment by patchthecode** [comment] 2018-11-27 16:57
ok i must have misunderstood. Giving this a 2nd look.

**Comment by patchthecode** [comment] 2019-01-17 19:11
Apologies for the late response. 
I was caught up between projects, and added to this, i do not know how to use patches.
I prefer just zipping a project and drag the zip file in here.

In any case, i did the changes in the patches manually.
And it works....
Im confused on what the problem is.

In any case, i took a while to respond to this, so im not sure if youve move on from this already.
I will say that im back to checking my issues daily again though.
i'll be on here today for quick response -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment] 2019-03-12 19:12
any update on this?

**Comment by fenuks** [comment] 2019-03-14 11:50
Hello, I created [fork](https://github.com/fenuks/JTAppleCalendar) with commit to reproduce the bug on top it. As said, to do that one has to select `Range selection` calendar, click 31 Jan cell, then 1st Feb (on the same screen, `didSelectDate` is triggered with cell for 1st Jan), and then again 1st (in `didDeselect` date I programmatically deselect all dates in selected range, and then select that clicked date, and `didSelectDate` caused by this operation has `cell == nil`.

**Comment by patchthecode** [comment] 2019-03-14 14:42
ok. I did the following steps

1. I click 31 jan
2. i click feb 1 (on same screen)
3. i click feb 1 again (on same screen)

behavior seen
in `didSelect` cell _is_ nil.
But this is expected. You programatically selected the cell -> feb 1st

Therefore the library will programatically select the cell feb 1st.
The feb1st outDate is on the screen, but the real feb1st monthDate is **off** off the screen.

Whenever a programatic selection is done, the monthDates are selected (not inDates/outDates). Therefore it selected the monthDate which is off the screen. This is expected.

What problem is this causing for you?

**Comment by fenuks** [comment] 2019-03-14 15:00
It's problematic, because I would like to style visible cell upon selection regardless whether it was selected with tap (which is possible) or programmatically (which is not possible with this kind of behaviour). I understand your rationale, it makes sense, but is also problematic. One would expect that if cell is visible on screen, no matter if it is monthDate or outDate, would be handled over.

To get around this limitation, I would have to keep map with all visible dates in month screen, and get the cell from map, if it's in/outMonth, yet visible.

**Comment by patchthecode** [comment] 2019-03-14 15:53
No, this should not happen.

Have you implemented the `willDisplayCell` function?
Just checking, becuase even with the instructions on the main page in bold text, some devs still miss it.

Did you by chance implement it?
Since the monthDate was selected, and not inDates/outDates, the library knows that it has to update the inDates/Outdates. Therefore it _should_ call the willDisplayCell function for the outDate.
This will give you a chance to update the cell as necessary.

let me know

**Comment by fenuks** [comment] 2019-03-15 11:47
Yes, I have implemented `willDisplayCell`. But I was doing most heavy lifting in `didSelectDate`, and I now tested, and `willDisplayCell` always gives me cell, even for outDates, which allows me to work around this problem. Thanks!

**Comment by patchthecode** [comment] 2019-03-15 13:56
awesome. closing this issue now.

**Closed by patchthecode** 2019-03-15 13:56 UTC
Labels: Awaiting User Input
