### ISSUE TITLE
deselectAllDates with triggerSelectionDelegate: false and selectDates with triggerSelection false and keepSelection false not working after upgrading to Xcode 9 and iOS 11

### ISSUE THREAD

**Issue by cazares** [patchthecode/JTAppleCalendar#615] opened 2017-11-07 20:11 UTC
1. I am using v7.1.2 of JTAppleCalendar

2. Yes, I'm using the latest.

3. First off, thank you so much for all the work you put into this library! I love it and so do our customers! 
NOTE: this WAS working before. Upon upgrading to Xcode 9/iOS 11, this issue now happens where 
**deselectAllDates(triggerSelectionDelegate: false)** 
is not working. Also, 
**selectDates(from, to, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)**
doesn't seem to work either. Let me try and explain my implementation a bit to better show you the issue.

<img width="309" alt="almostcompletecal" src="https://user-images.githubusercontent.com/1907954/32515034-61495516-c3c4-11e7-9cf1-64e968dd525b.png">
Upon startup, the last 7 days are selected programmatically. Notice there's two synced textfields at the top showing from and to dates. This is working fine.

<img width="309" alt="almostcompletecal" src="https://user-images.githubusercontent.com/1907954/32515065-7e914a3e-c3c4-11e7-8b37-a266898c35de.png">
If I select a date outside the initial range, a new range is made with from and to equal to each other (this is the start of a new range). Notice that the synced textfields are correct, but Nov. 1 through Nov. 7 did not get deselected. This is the first issue.

<img width="309" alt="almostcompletecal" src="https://user-images.githubusercontent.com/1907954/32515149-cc0ba318-c3c4-11e7-96ab-1c015c620123.png">
The second issue is that selectDates isn't selecting a range of dates like it used to. Notice in this screenshot that we expect Mon, Oct 09 through Fri, Oct 13 to be the range, Oct 10, 11, and 12 are not selected.

Here is a link to my gist including relevant code:
[https://gist.github.com/cazares/d8f8da366e0fe803a15f5bcdb865a9eb](https://gist.github.com/cazares/d8f8da366e0fe803a15f5bcdb865a9eb)

I've been working on this all day and I can't seem to get anywhere. Any help is greatly appreciated!

**Comment by patchthecode** [comment] 2017-11-07 22:06
hey i think the link to you code gist is not working. Got the link?

**Comment by patchthecode** [comment] 2017-11-07 22:30
Also, did you implement a `shouldSelect` or `shouldDeselect` function?
This now gets called when you do a selection or deselection.
?

**Comment by cazares** [comment] 2017-11-07 22:50
Try now. Also, no I don't implement shouldSelect or shouldDeselect, should I?

**Comment by patchthecode** [comment] 2017-11-07 23:45
@cazares ok i'll look at your code more in detail after work.
You do not have to implement shouldSelect or shouldDeselect. I just asked to further determine the source of your issue.

Since you updated to the latest version. Did you implement the `willDisplayItem` function?
The one *must* be implemented according to this -> https://github.com/patchthecode/JTAppleCalendar/issues/553

**Comment by cazares** [comment] 2017-11-08 00:40
This one?
`func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath)`
Yes, but it's an empty implementation.

**Comment by cazares** [comment] 2017-11-08 00:46
Hey I fixed the problem by doing this in `willDisplay cell`:
`cell.isSelected = isInsideDateRange(date)`
Thanks for pointing me in the right direction!

**Comment by patchthecode** [comment] 2017-11-08 00:57
@cazares one thing. try to use the `cellState.isSelected` instead of `cell.isSelected`

on that same link -> https://github.com/patchthecode/JTAppleCalendar/issues/553 on problem # 2, i explained why.
I am working on an update soon that will allow developers to use the `isSelected` directly on a cell. But I have not coded it yet. I'll finish it soon.

**Comment by cazares** [comment] 2017-11-08 01:00
For this:
`cellState.isSelected = isInsideDateRange(date)`
I get "Cannot assign to property: 'isSelected' is a 'let' constant

**Comment by cazares** [comment] 2017-11-08 01:48
Can you give an example how to change isSelected from `cellState`?

**Comment by patchthecode** [comment] 2017-11-08 15:01
OK. wait, i thought you were just doing a simple check to see if a cell was selected or not.

I might have been mistaken. What are you doing with the `isSelected` of a cell? Are you trying to select the cell by setting `cell.isSelected = true` ?
I am not clear what you are doing.

**Comment by cazares** [comment] 2017-11-08 19:26
Yes I am just looking for different ways to deselect and select a range of cells other than `deselectAllDates(triggSelectionDelegate: false)` and `selecctDates(from, to, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)`. These two functions were working before, but now they are not. Seems like `keepSelectionIfMultiSelectionAllowed: false` is not being respected.

**Comment by patchthecode** [comment] 2017-11-08 20:00
is it possible you can join chat here? https://gitter.im/patchthecode/JTAppleCalendar
typing here is too slow.
But yes, 

```swift
deselectAllDates(triggSelectionDelegate: false)
```
and
```swift
selectDates(from, to, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)
```

Should work. If this does not work, then I need to fix something. Let's not do a work around for something as important as this. I fix issues no matter how small they seem. And this sounds like a huge issue.

1. Selecting dates work by using any of the `selectDate` functions
2. Deselection works by either calling `deselectAllDates` or (if youre in multiselect mode) by calling a selectDate function again.

**Comment by cazares** [comment] 2017-11-08 20:08
Yes I will join shortly.

**Comment by cazares** [comment] 2017-11-08 20:57
I know we have a chat later, but I just wanted to mention that I found out that reverting to any version of JTAppleCalendar between 7.0.0 and 7.0.6 all work. Version 7.1.0 is the first version where my functionality breaks, all the way up to 7.1.3 (all 7.1 versions are broken).

**Comment by patchthecode** [comment] 2017-12-31 18:47
Closing issue until user responds.
I could not reproduce this in version 7.1+

**Closed by patchthecode** 2017-12-31 18:47 UTC
Labels: Awaiting User Input
