### ISSUE TITLE
Incorrect cellState.selectedPosition for specific sell

### ISSUE THREAD

**Issue by handioq** [patchthecode/JTAppleCalendar#280] opened 2017-02-01 08:21 UTC
Hello there one more time :D Sorry for a lot of issues.

Okey, i found bug (as i think) with selected position of cellState for the cell if cell is the first sunday of the month. This cell should be as **.full** selectedPosition as i understand. It is produced only if the month starts with Sunday (or another first day of week?).

I can catch this case as:

```
if (cellState.day == DaysOfWeek.sunday && cellState.text == "1") {
        
}
```

And for best understanding of such problem i post the image
![ym3h9v2iqee2r9tx5bqx0pev8-0ywsq4imqrhdyjrpc](https://cloud.githubusercontent.com/assets/2439146/22513293/abe648ea-e850-11e6-86d3-33122308e6c9.png)

**Comment by patchthecode** [comment] 2017-02-01 16:40
Ok. this is a real issue. 
I know the solution.
I'll code a fix this weekend for the latest (or earlier if im free)

**Comment by KyleConway** [comment] 2017-02-04 00:35
@patchthecode I am able to reproduce this issue as well. In addition to the use case described above, I am also seeing similar behavior when selecting outdate and indate cells. For instance, I have a vertically enabled calendar with rangeSelectionWillBeUsed and allowsMultipleSelection both enabled. Within the didSelectDate delegate callback, I am using "selectDates(from startDate: Date, to endDate: Date, triggerSelectionDelegate: Bool = true, keepSelectionIfMultiSelectionAllowed: Bool = false) {...}" to select the new range of dates (done similar to your multiple selection tutorial). If I enter the calendarView screen (no pre-selected dates) and select an outdate, everything is drawn fine. But if I then select another outdate 2 cells later in the calendar, the two newly selected cells are displayed fine but the first selected cell is not redisplayed. I want a bubble effect on the selected range of dates and need the first selected date to redraw. Attached is a screen shot of the result for reference. This is not the case with the monthly dates - I am only seeing this behavior for indates and outdates. Let me know if you need any more details. 
![screen shot 2017-02-03 at 4 32 38 pm](https://cloud.githubusercontent.com/assets/2515053/22613596/69d9b696-ea2e-11e6-8054-35e64033c50e.png)

**Comment by tungfam** [comment] 2017-02-05 12:27
@patchthecode I've made `pod update` to version `6.1.2` but still see the incorrect `selectedPosition` for the dates such as 1st May 2017th. Did I miss anything? Thanks!

**Comment by patchthecode** [comment] 2017-02-05 15:23
@tungfam it update was done on master branch. 
You need this in your pod file ->
```swift
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```
when doing a pod update.

If youre online, can you message me here -> https://gitter.im/patchthecode/JTAppleCalendar
Chatting there is faster.

**Comment by patchthecode** [comment] 2017-02-05 15:34
So for example:
```   
    *   *   *   *
A | B | C | D | E | F
```
If B, C, D and E are selected. The selected position of:
1. B = left
2. C = middle
3. D = middle
4. E = right
5. A and F  = none

The job of selectedPosition() is to return the `selectedPosition`. The Job of selected position is **not** to create a range.
We use `selectedPosition` to help us to create a range.

So when you say that you are getting the incorrect selectedPosition, then answer me this -->
Is the position that you are getting different from what is described above?

**Comment by KyleConway** [comment] 2017-02-06 19:32
@patchthecode I have updated my PodFile to point to master as you described above. I wiped my pods and reinstalled. The fix is not correct for the issue that I described.

Referencing the use case and image that I posted before: I have a handleCellDisplay(dayCellView: JTAppleDayCellView?, cellState: CellState, date: Date) {...} func that is called from "willDisplayCell", "didDeselectDate", and "didSelectDate" delegate callbacks similar to the tutorials. When I enter the calendarView with no dates preselected - then I select the date 3/1/2017. After I then select 3/3/2017. These are both outdates in my calendar and I see the same result shown in my attached image above. I added a print statement to handleCellDisplay - this is what I am seeing:

handleCellDisplay -- date: 2017-03-01 08:00:00 +0000, selectedPosition: full
——— End of first selection (3/1/2017) display 
handleCellDisplay -- date: 2017-03-03 08:00:00 +0000, selectedPosition: right
handleCellDisplay -- date: 2017-03-02 08:00:00 +0000, selectedPosition: middle
——— End of second selection (3/3/2017) display

From the print statements you can see the first date 3/1/2017 is not being redisplayed on the second selection of date 3/3/2017. In contrast, if I do the same steps with visible current month dates and not indates or outdates I am seeing this output. Referencing the above attached image, the dates I am using are 2/26/2017 and 2/28/2018:

handleCellDisplay -- date: 2017-02-26 08:00:00 +0000, selectedPosition: full
——— End of first selection (2/26/2017) display 
handleCellDisplay -- date: 2017-02-28 08:00:00 +0000, selectedPosition: right
handleCellDisplay -- date: 2017-02-26 08:00:00 +0000, selectedPosition: left
handleCellDisplay -- date: 2017-02-27 08:00:00 +0000, selectedPosition: middle
handleCellDisplay -- date: 2017-02-28 08:00:00 +0000, selectedPosition: right
——— End of second selection (2/28/2017) display

You can see in the second date selection redisplay that the first date selected (2/26/2017) is being redisplayed correctly - its selectedPosition is updated from "full" to "left". This is not happening with the selection of indates or outdates and only correctly redisplaying with visible month dates. 
Let me know if you need any more details - thank you for all the help.

**Comment by patchthecode** [comment] 2017-02-06 20:02
@KyleConway ok. I think i did the fix for the first issue, and i kept my fingers crossed hoping it will fix your issue 😆 . 
Let me look into you use-case now.

**Comment by patchthecode** [comment] 2017-02-07 05:36
@KyleConway ok after looking into your issue, i do not think what you are experiencing is a bug (unless i am wrong).

You are using this to select right?
```swift
calendarView.selectDates(from: someStartDate, to: someEndDate,  triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
```

I think what you need is just this:
```swift
calendarView.selectDates(from: someStartDate, to: someEndDate)
```

I think in your code, you are not triggering the delegate

**Comment by patchthecode** [comment] 2017-02-07 16:30
@KyleConway that said, i did find another issue with range selection I am currently fixing. If the code suggested above does not resolve your problem, then this next fix will.

**Comment by KyleConway** [comment] 2017-02-07 17:56
That update to my implementation of selectDates looks to have done it. Thank you for the feedback! I'm still interested in the fix you described - will there be a new release once your change is applied? I only ask because I am using pods and 6.1.2 does not include a lot of the latest enhancements. I am pointing to master in the mean time

**Comment by patchthecode** [comment] 2017-02-07 20:54
@KyleConway you can stay on master branch. I will make an official release once i finish that last logic change with range selection. So official version might be released in about 1 week? more or less.

**Comment by handioq** [comment] 2017-02-08 14:58
@patchthecode 
I tried and got this result:

![](http://savepic.ru/12889356.png)

But if I select some day of second week I get expected result:

![](http://savepic.ru/12893452.png)

**Comment by patchthecode** [comment] 2017-02-21 17:14
closing this as the original issue has been resolved.

**Closed by patchthecode** 2017-02-21 17:14 UTC
Labels: Already Fixed on Master Branch, bug

**Comment by tungfam** [comment] 2017-02-21 17:17
@patchthecode sounds good! thanks a lot! where is the path to the latest branch that i can pull from to have this update?

**Comment by patchthecode** [comment] 2017-02-21 18:05
The original issue has been solved.

But your issue with the correct way to display `selectedPosition()`  will be racked here -> https://github.com/patchthecode/JTAppleCalendar/issues/280#issuecomment-281411889

**Comment by patchthecode** [comment] 2017-02-21 18:10
@tungfam leave a comment on that page you will be notified of the changes. I have only now gotten to this issue as there were others to resolve
