### ISSUE TITLE
Broken cell refresh after rangeSelection v6.1.5

### ISSUE THREAD

**Issue by jamesjmtaylor** [patchthecode/JTAppleCalendar#354] opened 2017-03-22 05:05 UTC
![cellrefresh](https://cloud.githubusercontent.com/assets/17860994/24199590/6be9df3e-0ec7-11e7-82ac-65513a0a7f50.gif)

I've searched the tutorials and guides as well as the open & closed issues. 
My program has a couple issues right now, all demonstrated by the video link in the link above & pasted pictures:
1) Previous versions 'canSelectDate' prevented selection of dates before today; now it doesn't
2) Sometimes cell range selection garbles the cellState.selectedPosition(), leading to bizarre range depictions.

Any help you can provide is appreciated.  My most pertinent functions are below.

```swift
       override func viewDidLoad() {
        super.viewDidLoad()
        calendarView.dataSource = self
        calendarView.delegate = self
        calendarView.registerCellViewXib(file: "CalendarCellView")
        calendarView.registerHeaderView(xibFileNames: ["MonthHeaderView"])
        calendarView.allowsMultipleSelection  = true
        calendarView.rangeSelectionWillBeUsed = true
        calendarView.scrollingMode = .none
        calendarView.scrollDirection = .vertical
        calendarView.cellInset = CGPoint(x: 0, y: 0)

    }

    // MARK: - Buttons
    @IBAction func cancelButtonPressed(_ sender: Any) {
        dismiss(animated: true, completion: nil)
    }
    @IBAction func clearAllButtonPressed(_ sender: Any) {
        arrivalDateLabel.text = "Arrival Date"
        departureDateLabel.text = "Departure Date"
        firstDate = nil
        calendarView.deselectAllDates()
        calendarView.reloadData()
        
    }
    @IBAction func saveButtonPressed(_ sender: Any) {
    }
    
    // MARK: - JTAppleCalendar Calendar setup
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        //Set<Calendar.Component>
        var components = Calendar.current.dateComponents([Calendar.Component.month, Calendar.Component.year], from: Date())
        components.day = 1
        let startDate = Calendar.current.date(from: components) ?? Date()
        let endDate = Date(timeIntervalSinceNow: TimeInterval(60*60*24*180))
        // Only 1-6 allowed for numberOfRows
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6,
                                                 calendar: Calendar.current,
                                                 generateInDates: .none,
                                                 generateOutDates: .none,
                                                 firstDayOfWeek: .sunday)
        return parameters
    }
    
    // MARK: - JTAppleCalendar Header setup
    // Height of the header
    func calendar(_ calendar: JTAppleCalendarView, sectionHeaderSizeFor range: (start: Date, end: Date), belongingTo month: Int) -> CGSize {
        return CGSize(width: 200, height: 40)
    }
    // Text format of the header
    func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
        let headerCell = (header as? MonthHeaderView)
        formatter.dateFormat = "MMMM yyyy"
        headerCell?.monthLabel.text = formatter.string(from: range.start)
    }
    
    // MARK: - JTAppleCalendar Cell setup
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        let calendarCellView = cell as! CalendarCellView
        calendarCellView.dayLabel.text = cellState.text
        
        formatter.dateFormat = "MM/dd/yyyy"
        let currentDateString = formatter.string(from: Date())
        let cellStateDateString = formatter.string(from: cellState.date)
        
        if currentDateString == cellStateDateString && firstDate == nil { //Highlight the current day (only if user hasn't picked yet)
            calendarCellView.selectedView.layer.cornerRadius = 28
            calendarCellView.selectedView.layer.borderColor = UIColor.white.cgColor
            calendarCellView.selectedView.layer.borderWidth = 2
            calendarCellView.selectedView.backgroundColor = UIColor.init(displayP3Red: 224, green: 224, blue: 224, alpha: 0.21)
            calendarCellView.selectedView.isHidden = false
        } else {
            if cellState.dateBelongsTo == .thisMonth { //Hide days outside of the current month
                calendarCellView.isHidden = false
            } else {
                calendarCellView.isHidden = true
            }
            handleCellTextColor(view: calendarCellView, cellState: cellState) //selection overrides all presets
            handleSelection(cell: calendarCellView, cellState: cellState) //selection overrides all presets
        }
    }
    
    //Prevent selecting dates in the past
    func calendar(_ calendar: JTAppleCalendarView, canSelectDate date: Date, cell: JTAppleDayCellView, cellState: CellState) -> Bool {
        if  date < Date() { //Prevent selection of past dates
            return false
        } else { //Allow selection
            return true
        }
    }
    
    //Enables selecting a range between firstDate and whatever's selected next
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
        if firstDate != nil {
            if firstDate! < date { //use firstDate on left to select left to right
                formatter.dateFormat = "d MMMM"
                arrivalDateLabel.text = formatter.string(for: firstDate!)
                departureDateLabel.text = formatter.string(for: date)
                calendarView.selectDates(from: firstDate!,
                                         to: date,
                                         triggerSelectionDelegate: false,
                                         keepSelectionIfMultiSelectionAllowed: true)
            } else { //use firstDate on right to select left to right
                formatter.dateFormat = "d MMMM"
                arrivalDateLabel.text = formatter.string(for: date)
                departureDateLabel.text = formatter.string(for: firstDate!)
                calendarView.selectDates(from: date,
                                         to: firstDate!,
                                         triggerSelectionDelegate: false,
                                         keepSelectionIfMultiSelectionAllowed: true)
            }
        } else {
            formatter.dateFormat = "d MMMM"
            firstDate = date
            arrivalDateLabel.text = formatter.string(for: firstDate)
            handleSelection(cell: cell, cellState: cellState)
            handleCellTextColor(view: cell, cellState: cellState)
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
        handleSelection(cell: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
    }
    
    // Handles the text color of the cell
    func handleCellTextColor(view: JTAppleDayCellView?, cellState: CellState) {
        guard let calendarCellView = view as? CalendarCellView  else {
            return
        }
        if cellState.isSelected {
            calendarCellView.dayLabel.textColor = UIColor.green
        } else {
            calendarCellView.dayLabel.textColor = UIColor.white
        }
    }
    
    // Function to handle the calendar selection
    func handleSelection(cell: JTAppleDayCellView?, cellState: CellState) {
        //JTAppCal returns nil if selection is outside of the current month
        //This avoids the crash
        guard let calendarCellView = cell as? CalendarCellView else {
            return
        }
        switch cellState.selectedPosition() {
        case .full: //For a standalone cell
            calendarCellView.selectedView.isHidden = false
            calendarCellView.selectedView.layer.cornerRadius = 28
        case .middle: //For a cell with selected dates to left and right
            calendarCellView.selectedView.isHidden = false
        case .left: //For a cell on the left end
            calendarCellView.selectedView.isHidden = false
            generateCurve(viewToRound: calendarCellView.selectedView, corner1:.topLeft, corner2:.bottomLeft)
        case .right: //For a cell on the right end
            calendarCellView.selectedView.isHidden = false
            generateCurve(viewToRound: calendarCellView.selectedView, corner1:.topRight, corner2:.bottomRight)
        default: //unselected cell?
            calendarCellView.selectedView.isHidden = true
            calendarCellView.selectedView.backgroundColor = nil
        }
    }
    
    func generateCurve(viewToRound: UIView, corner1: UIRectCorner, corner2: UIRectCorner) {
        let path = UIBezierPath(roundedRect:viewToRound.bounds,
                                byRoundingCorners:[corner1, corner2],
                                cornerRadii: CGSize(width: 28, height: 28))
        let maskLayer = CAShapeLayer()
        
        maskLayer.path = path.cgPath
        viewToRound.layer.mask = maskLayer
    }
}
```

**Comment by patchthecode** [comment] 2017-03-22 05:22
> Previous versions 'canSelectDate' prevented selection of dates before today; now it doesn't
I have been slowly trying to make the function names more  consistent.
the `canSelectDate` date function is no more called by that name.
here is the new function

```swift
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleDayCellView, cellState: CellState) -> Bool
```

> Sometimes cell range selection garbles the cellState.selectedPosition(), leading to bizarre range depictions. Looking into this right now.

**Comment by patchthecode** [comment] 2017-03-22 05:39
That video link is broken. But you can describe the 2nd problem more when i'm online.
I'm usually here all day  -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment] 2017-03-23 09:42
Updated the code.

**Comment by jamesjmtaylor** [comment] 2017-03-23 13:13
Cool beans.  I'll 'pod install' again and let you know.

**Comment by patchthecode** [comment] 2017-03-23 16:06
The code update should have fixed the reload bug.

The visual glitch was caused by this code:

```swift
        switch cellState.selectedPosition() {
        case .full: //For a standalone cell
            calendarCellView.selectedView.isHidden = false
            calendarCellView.selectedView.layer.cornerRadius = 28
            calendarCellView.selectedView.backgroundColor = UIColor.white
        case .middle: //For a cell with selected dates to left and right
            calendarCellView.selectedView.isHidden = false
            calendarCellView.selectedView.backgroundColor = UIColor.white
        case .left: //For a cell on the left end
            calendarCellView.selectedView.isHidden = false
            generateCurve(viewToRound: calendarCellView.selectedView, corner1:.topLeft, corner2:.bottomLeft)
            calendarCellView.selectedView.backgroundColor = UIColor.white
        case .right: //For a cell on the right end
            calendarCellView.selectedView.isHidden = false
            generateCurve(viewToRound: calendarCellView.selectedView, corner1:.topRight, corner2:.bottomRight)
            calendarCellView.selectedView.backgroundColor = UIColor.white
        default: //unselected cell?
            calendarCellView.selectedView.isHidden = true
            calendarCellView.selectedView.backgroundColor = nil
        }


Remember, you are dequeueing cells. Therefore cells are being reused.
So if originally, you have called `generateCurve` on one cell's `selectedView`.
If that cell is being reused by another cell, the curve will be there.
This is similar to how a UITableView or a UICollectionView works.
You should reset the cell fully.
```

**Comment by jamesjmtaylor** [comment] 2017-03-23 23:21
It works now!  I just had to change that code snippet that you posted above to the code below. Thanks for all your help man. `        calendarCellView.selectedView.isHidden = true
        calendarCellView.selectedView.layer.cornerRadius = 0
        calendarCellView.selectedView.backgroundColor = UIColor.clear
        calendarCellView.selectedView.layer.mask = nil
        switch cellState.selectedPosition() {
        case .full: //For a standalone cell
            calendarCellView.selectedView.isHidden = false
            calendarCellView.selectedView.layer.cornerRadius = 28
            calendarCellView.selectedView.backgroundColor = UIColor.white
        case .middle: //For a cell with selected dates to left and right
            calendarCellView.selectedView.isHidden = false
            calendarCellView.selectedView.backgroundColor = UIColor.white
        case .left: //For a cell on the left end
            calendarCellView.selectedView.isHidden = false
            generateCurve(viewToRound: calendarCellView.selectedView, corner1:.topLeft, corner2:.bottomLeft)
            calendarCellView.selectedView.backgroundColor = UIColor.white
        case .right: //For a cell on the right end
            calendarCellView.selectedView.isHidden = false
            generateCurve(viewToRound: calendarCellView.selectedView, corner1:.topRight, corner2:.bottomRight)
            calendarCellView.selectedView.backgroundColor = UIColor.white
        default: //unselected cell?
            calendarCellView.selectedView.isHidden = true
            calendarCellView.selectedView.backgroundColor = nil
        }`

**Comment by patchthecode** [comment] 2017-03-23 23:25
Awesome. I'll close this issue.
If you find anything else, then do let me know.

**Closed by patchthecode** 2017-03-23 23:25 UTC
Labels: Already Fixed on Master Branch, bug
