### ISSUE TITLE
selectDates function triggering didSelectDate with different date?

### ISSUE THREAD

**Issue by Eric0625** [patchthecode/JTAppleCalendar#345] opened 2017-03-16 11:17 UTC
I'm using selectDates function to select a date from code, and hoping to trigger the related delegate, but when I debug the code I find the delegate receives another date, why could that happen?
![1](https://cloud.githubusercontent.com/assets/18132007/23993783/e72d680e-0a7c-11e7-8947-ca3ed67b47f5.PNG)

![2](https://cloud.githubusercontent.com/assets/18132007/23993793/f9a44e76-0a7c-11e7-9949-4efa5d34f46e.PNG)

**Comment by Eric0625** [comment] 2017-03-16 11:23
here is the configuration of calendar

`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {     
  
        let startDate = Date() 
        let endDate = calendarView.currentCalendar.date(byAdding: .day, value: 14, to: startDate)!
        return ConfigurationParameters(startDate: startDate,
                                       endDate: endDate,
                                       numberOfRows: 1, // Only 1, 2, 3, & 6 are allowed
            calendar: calendarView.currentCalendar,
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: .monday)
    }`

**Comment by patchthecode** [comment] 2017-03-16 16:15
When ever you are looking at dates on the console, or on the debugger, wrong dates can be displayed. In order to see correct dates, you need to use a `DateFormatter` instead. Look here and at the discussion and let me know if the issue is resolved --> https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by Eric0625** [comment] 2017-03-16 16:57
@patchthecode thx for replying and providing the reference. But I don't really care what the date string displays. I've noticed the output is not my local date, but even if they're produced from console's date configuration, should they match at those two places which I captured in the pics?

**Comment by Eric0625** [comment] 2017-03-16 17:16
I just tested the code again. Now they are the same on the console, not matching my local time, but at least the same. So the problems seems to happen at specific time, I'm gonna check it at the same time again, to see if it happens.

**Comment by patchthecode** [comment] 2017-03-16 17:50
@Eric0625 

in this function

<-- Look at the calendar you are providing.

```swift
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {     
  
        let startDate = Date() 
        let endDate = calendarView.currentCalendar.date(byAdding: .day, value: 14, to: startDate)!
        return ConfigurationParameters(startDate: startDate,
                                       endDate: endDate,
                                       numberOfRows: 1, 
            calendar: calendarView.currentCalendar, // <--- LOOK AT THIS
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: .monday)
    }
```

` calendar: calendarView.currentCalendar,`

The `calendarView.currentCalendar` should be a calendar that is configured to match the time zone of the dates that you want to work with.

can you try putting this instead?
` calendar:  Calendar.current,`

If you **are** aready using Calendar.current, then help me test it by doing the following:
I need to know your time zone so that I can configure a calendar to match yours.
Therefore, can you put this code somewhere and run it?

```
let cal = Calendar.current
//PUT A DEBUG BREAKPOINT ON THE LINE BELOW
print("")
```

When the debugger console pops up, type "po cal"
It should print out a log that looks like this:
```
▿ gregorian (fixed)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "fixed"
  ▿ locale : Optional<Locale>
    ▿ some : en_PH (fixed)
      - identifier : "en_PH"
      - kind : "fixed"
  ▿ timeZone : Asia/Manila (fixed)
    - identifier : "Asia/Manila"
    - kind : "fixed"
    ▿ abbreviation : Optional<String>
      - some : "GMT+8"
    - secondsFromGMT : 28800
    - isDaylightSavingTime : false
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1
```

Can you copy the Text of this and paste it here for me please?

**Comment by Eric0625** [comment] 2017-03-17 01:11
hi there 

1. calendar: calendarView.currentCalendar is Calendar.current, I just wrapped it
2. the output is:
▿ gregorian (current)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "current"
  ▿ locale : Optional<Locale>
    ▿ some : en_US (current)
      - identifier : "en_US"
      - kind : "current"
  ▿ timeZone : Asia/Shanghai (current)
    - identifier : "Asia/Shanghai"
    - kind : "current"
    ▿ abbreviation : Optional<String>
      - some : "GMT+8"
    - secondsFromGMT : 28800
    - isDaylightSavingTime : false
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1

**Comment by patchthecode** [comment] 2017-03-18 15:31
Thanks, will envestigate.

**Comment by boborbt** [comment] 2017-03-21 09:33
A possibly related problem: in my app when I select a date programmatically, the didSelect method always receives cellStates that report the date being in "thisMonth" even when they are way past the current month (even when they are not even visible).

If you believe that this is a separate problem I can open a new issue.

**Comment by patchthecode** [comment] 2017-03-21 09:48
@boborbt that sounds like a totally new issue.
open a separate one, i'll look into it in the morning.

**Comment by boborbt** [comment] 2017-03-21 11:00
ok

**Comment by patchthecode** [comment] 2017-03-29 04:01
closing Issue

**Closed by patchthecode** 2017-03-29 04:01 UTC
