### ISSUE TITLE
DateCell UI is updating only after Display or after scrolling ended

### ISSUE THREAD

**Issue by anushak89** [patchthecode/JTAppleCalendar#587] opened 2017-10-13 16:16 UTC
Hello,

I'm using latest version (7.0.6) of your library via CocoaPods.

I'm facing an issue while scrolling between months. For some dates I have a different UI / color and I am updating this on `func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell` delegate method. But it is changing only after the scrolling is ended.

May be I can use different custom cells for different type of dates. Could you please let me know if you have any other ways to fix this or I missed some settings?

Thanks,
Anusha

**Comment by patchthecode** [comment] 2017-10-13 16:59
Hmm. ok.
Can you paste me the relevant parts of your `cellForItemAt` functon?

**Comment by anushak89** [comment] 2017-10-13 17:29
```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        
        // Setup text color
        if cellState.dateBelongsTo == .thisMonth {
            
            let dateCell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "DateCell", for: indexPath) as! CalendarCellView
            
            if Calendar.current.isDateInToday(cellState.date) {
                
                dateCell.todayImageView.image = UIImage(named: "Today dot")
                
            } else {
                
                dateCell.todayImageView.image = nil
            }
            
            // Setup Cell text
            dateCell.dayLabel.text = cellState.text
            dateCell.dayLabel.textColor = UIColor(colorWithHexValue: 0xECEAED)
            
            let day = Int(dateCell.dayLabel.text!)
            
            if let currentShift = self.shifts[day!]?.last {
                
                dateCell.shift = currentShift
            } else {
                
                dateCell.shift = nil
            }
            
            // Set Shift Image
            dateCell.shiftImageView.image = self.getHighlightImage(date: day!)
            
            if selectedDates.count > 0 && selectedDates.contains(date) {
                
                dateCell.isSelectedCell = true
                
            } else {
                
                dateCell.isSelectedCell = false
            }
            
            return dateCell
            
        } else {
            
            let outDateCell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "OutDateCell", for: indexPath) as! CalendarCellView
            return outDateCell
        }
    }
```

**Comment by patchthecode** [comment] 2017-10-13 18:14
What version of the library are you using. 7.0.6?
Also, is this the line of code you are talking about with the color?
```swift
dateCell.dayLabel.textColor = UIColor(colorWithHexValue: 0xECEAED)
```
If looks like you are setting a text color to all monthDates.
This code looks normal.

Are you saying that the cell text color is only being set after you scroll?

**Comment by anushak89** [comment] 2017-10-13 18:41
No, the cell highlight image. It's depends on added shift on that date.

**Comment by patchthecode** [comment] 2017-10-13 18:46
OK
```swift
dateCell.shiftImageView.image = self.getHighlightImage(date: day!)
```
Is the `getHighlightImage` taking a while to execute because of some server connection or some long execution?

If this function grabs the image immediately, then there should be no problem. If it takes a while, then this may be out of the control of the library. Can you confirm if this function is slow or not?

**Comment by anushak89** [comment] 2017-10-13 18:55
This function is checking some stored properties only. May be all conditional things in the delegate method makes it slow. Let me try with different custom cells. Thanks!

**Comment by patchthecode** [comment] 2017-10-13 19:07
the `cellForItemAt` function by itself looks light-weight. Its not bad. I doubt it is the cause of the slow image.
However, i do not know what is in this function --> `getHighlightImage`
Is that the one that has many conditional things?
let me know.

in the mean time i'll close this issue.
But if you find anything then reply here and i'll re-open if it turns out to be a calendar issue.

**Closed by patchthecode** 2017-10-13 19:07 UTC
