### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by jonfabris** [patchthecode/JTAppleCalendar#228] opened 2016-12-13 17:54 UTC
I am using version 6.0.0

I am getting several of these errors:

/Users/developer/Documents/workspace/graypeakios/Pods/JTAppleCalendar/Sources/JTAppleCalendarView.swift:832:48: Binary operator '>=' cannot be applied to operands of type 'Date' and 'Date!'
/Users/developer/Documents/workspace/graypeakios/Pods/JTAppleCalendar/Sources/JTAppleCalendarView.swift:834:52: Binary operator '>=' cannot be applied to operands of type 'Date' and 'Date!'

**Comment by patchthecode** [comment] 2016-12-13 18:47
@jonfabris the latest version is 6.0.5
Use that one and the error will go away.

This error is caused by a known Swift issue. It was fixed in later versions.
Closing this issue. If you are still having errors after updating to 6.0.5 then we can talk again :)

**Closed by patchthecode** 2016-12-13 18:47 UTC
