### ISSUE TITLE
Add JTAppleCalendar inside custom UIView with xib

### ISSUE THREAD

**Issue by Macaret** [patchthecode/JTAppleCalendar#1274] opened 2020-05-18 17:59 UTC
**(Required) Version Number: 8.0.3**

## Description
I added a JTAppleCalendar view inside a Custom xib UIView that is intended for reuse across the app. I followed the exact steps from the guide and I'm receiving the following error:

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindCell with identifier dateCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'`

I followed the same steps to add a calendar view to a UIViewController and everything works fine. But then I decided to move the Calendar to a Custom UIView for reuse, and I'm receiving the error. 

I did make sure I have added the dateCell identifier.

## Steps To Reproduce
* Add JTAppleCalendar view to a custom xib UIView;
* Add custom UIView with the calendar inside a view controller;
* try to run the app;

## Expected Behavior
I'm not sure if there is a limitation for the JTAppleCalendar to work only in UIViewControllers and not into a xib UIView. But I would expect for it to work.

**Comment by patchthecode** [comment] 2020-05-18 18:18
Do you have a base minimum sample app that show this issue?
The problem is simple but can be hard to track as it could be a code, xib, or storyboard problem.

**Comment by Macaret** [comment] 2020-05-20 04:41
I found out what the issue was. I first implemented the Calendar inside a ViewController with a prototype cell, and then copied the calendar to the custom UIView. But a UIView with xib does not support a prototype cell inside a collection (but it did show up without error after copying) and that's why it wasn't working.

**Comment by patchthecode** [comment] 2020-05-20 15:45
Awesome. Glad the issue was found. 
Closing this now.

**Closed by patchthecode** 2020-05-20 15:45 UTC
