### ISSUE TITLE
Problem with range.start and range.end

### ISSUE THREAD

**Issue by marioilianov94** [patchthecode/JTAppleCalendar#289] opened 2017-02-03 11:43 UTC
Hi,

I discover a problem with the last version of the library, I want to put the month name on the header on each month. 

I make a vertical scroll and itemSize = 50.

I use this to take the month on the header.
```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
        
        switch identifier {
        case "MonthHeaderFirstView":
            
            let headerCell = (header as? MonthHeaderFirstController)
            
            let startDate = range.start
            print("RANGE START: \(range.start)")
            
            let month = currentCalendar.dateComponents([.month], from: startDate).month!
      
            let year = currentCalendar.component(.year, from: startDate)
            
            headerCell?.firstMonthLabel.text = String(month) + " - " + String(year)
            break;
            
        case "MonthHeaderSecondView":
            let headerCell = (header as? MonthHeaderSecondController)
            
            let endDate = range.end
            print("RANGE END: \(range.end)")
            
            print("--------------------------")
            let month = currentCalendar.dateComponents([.month], from: endDate).month!
            
            let year = currentCalendar.component(.year, from: endDate)
            
            headerCell?.secondMonthLabel.text =  String(month) + " - " + String(year)
            
            break;
            
        default:
            let headerCell = (header as? MonthHeaderFirstController)
            
            let startDate = range.start
            
            let month = currentCalendar.dateComponents([.month], from: startDate).month!
            
            let year = currentCalendar.component(.year, from: startDate)
            
            headerCell?.firstMonthLabel.text =  String(month) + " - " + String(year)            
            break;
        }
    }
```

```swift
func calendar(_ calendar: JTAppleCalendarView, sectionHeaderIdentifierFor range: (start: Date, end: Date), belongingTo month: Int) -> String {
        if month % 2 > 0 {
            return "MonthHeaderFirstView"
        }
        return "MonthHeaderSecondView"
    }
```

But It has a problem on February and some months, the range start will return this "2017-02-28 23:00:00 +0000"

Here's a screenshot.
![image](https://cloud.githubusercontent.com/assets/9165412/22590186/42da8ea0-ea0e-11e6-8b28-f1ff9957a8a5.png)

I hope you can help me :)

Thanks.

**Comment by patchthecode** [comment] 2017-02-03 14:52
I do not understand the last part of your question.
You said
> the range start will return this "2017-02-28 23:00:00 +0000"

Which function is returning this?
Is it returning this for all the months?
Based on your question, I am not sure what the problem is. For me to know  the problem, I neeed to know what you are getting **and** what was supposed to be the expected result, and how they are different.

**Comment by marioilianov94** [comment] 2017-02-03 15:28
I want to put the month number on the header in the calendar, how can I do it?

My calendar shows max. 2 headers at the same time on the screen.

**Comment by patchthecode** [comment] 2017-02-03 16:38
I did this:

```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
        let date = range.start
        let month = testCalendar.component(.month, from: date)
        // etc etc
```

And it works well.
Can you tell me what version number of the calendar you are using?

**Comment by marioilianov94** [comment] 2017-02-03 16:42
I use the last versión 6.1.2.

I'll try your code later, I'll tell you if it works ;)

**Comment by marioilianov94** [comment] 2017-02-03 17:19
I can't try this now, I'll try it on Monday at Work.

I'll tell you if it works.
Thanks ;D

**Comment by marioilianov94** [comment] 2017-02-06 07:18
It works, thank you so much :D

**Comment by patchthecode** [comment] 2017-02-06 13:36
Awesome. I'll close this issue now.
Btw, you calendar looks very cool. Why dont you post its picture here --> https://github.com/patchthecode/JTAppleCalendar/issues/216 ?

cheers man.

**Closed by patchthecode** 2017-02-06 13:36 UTC
Labels: question
