### ISSUE TITLE
CellState.day isn't correct

### ISSUE THREAD

**Issue by Tumtrirat** [patchthecode/JTAppleCalendar#390] opened 2017-04-25 04:55 UTC
Version 7.0.1

I've follow and learn your tutorial in the youtube video. Everything seems to be ok until I check with real calendar.
start date is 2017 01 01
but the  shown day of the weeks weren't correct.
As you can see in the pic below 2017 01 01 is supposed to be Sunday but it was Saturday.

I've checked cellState.day and .text.(see below).
Is there any thing I can do to fix this.

I really appreciate your work.

![screen shot 2560-04-25 at 11 34 09 am](https://cloud.githubusercontent.com/assets/26209803/25369198/6eb2bda8-29ac-11e7-8e0f-cc31ce23ad2e.png)

**Comment by patchthecode** [comment] 2017-04-25 14:48
hmm. 
Is that image you showed  supposed to by January 1st 2017?
That does not seem to be right.
Can you provide a zipped copy of your project ?
You can drag the zip file into this chat box.

**Comment by Tumtrirat** [comment] 2017-04-25 16:41
[TestCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/955814/TestCalendar.zip)
Here you go.
Thank you very much for looking into this. :)

**Comment by patchthecode** [comment] 2017-04-27 16:34
So im finally free and checking up on this to resolve this quickly.
The zip file you sent me has 2 files missing :/ 

`CalendarViewController` and `CalendarCellView`

**Comment by Tumtrirat** [comment] 2017-04-27 23:44
I'm really sorry. I miss that. 
Here is the one with CalendarViewController and CalendarCellView
[TestCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/963148/TestCalendar.zip)

**Comment by patchthecode** [comment] 2017-04-28 04:58
I do not see any error with this. The image that you are seeing is the month of April 2017.
Here is the file. I added a header. If you are experiencing this issue still then chat with me here -> https://gitter.im/patchthecode/JTAppleCalendar

[TestCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/963476/TestCalendar.zip)

**Comment by Tumtrirat** [comment] 2017-04-29 14:22
You see, the image I'm seeing is the month of April 2017. But I set it to show the mont of January 2017 and after I've checked its cellState.date or the formatter.string(from: date) It shows this pic below
The selected cell.text is 6.
formatter.string(from: date) =2017 01 06 
cellState.date = 1471-01-05 17:04:35 +0000
![screen shot 2560-04-29 at 10 18 59 pm](https://cloud.githubusercontent.com/assets/26209803/25556146/4921d0fc-2d2a-11e7-8049-54cf91a54b67.png)

**Comment by patchthecode** [comment] 2017-04-29 14:24
Are you able to join me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment] 2017-04-29 14:57
Diagnosis:

User used 
```swift
let calendar = Calendar.current
```

This created a calendar with identifier `Buddhist` instead of `Gregorian`.
Therefore dates appeared wrong. :)

Solution: User simply had to create a calendar with identifier `Gregorian`.

Closing this issue as not a bug. 
Cheers 🍻

**Closed by patchthecode** 2017-04-29 14:57 UTC
Labels: Awaiting User Input

**Comment by zhanswift** [comment] 2017-09-26 11:19
Hello. I use Gregorian calendar. And now when I select date 7 septemper 2017 i get in debug:

> Selected Date: 2017-09-06 18:00:00 +0000
<img width="377" alt="2017-09-26 17 16 07" src="https://user-images.githubusercontent.com/16617536/30857703-974ee240-a2de-11e7-9a4d-e85774ada71c.png">

**Comment by patchthecode** [comment] 2017-09-26 17:51
@zhanswift what code are you using to print the debug date?

**Comment by zhanswift** [comment] 2017-09-27 03:50
I use this: 
       
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
	    print("Selected Date:", date)
    }

**Comment by patchthecode** [comment] 2017-09-27 06:53
@zhanswift this is not the correct way to print a date
You need to print a date to console using a date formatter. refer to this answer here for an explanation of how to do it -> https://github.com/patchthecode/JTAppleCalendar/issues/252

let me know if you are still stuck
