### ISSUE TITLE
didSelectDate not getting called

### ISSUE THREAD

**Issue by gabrielcandiag** [patchthecode/JTAppleCalendar#822] opened 2018-07-04 22:00 UTC
**Version 7.1.5**

Hi,

I was using the library without problems, and the last build that I made the didSelectDate method is not getting called. I've being using the same version of the library since the beginning. 

I'm using this configuration for the Delegate and the Datasource, I'm setting those up programatically.

If I put a breakpoint on the UICollectionViewDelegates cellForItem is getting called, but on the didSelectItemAt is not getting called. 
The delegate is not being deallocated or something, I already test that out.

Maybe you can give me some pointers in what can I do to fix this.

```
extension URCalendarDataProvider: JTAppleCalendarViewDataSource {
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let yearInSeconds: Double = 60*60*24*183
        let parameters = ConfigurationParameters(startDate: Date(), endDate: Date().addingTimeInterval(yearInSeconds), firstDayOfWeek: .monday)
        return parameters
    }
}

extension URCalendarDataProvider: JTAppleCalendarViewDelegate {
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let newCell = cell as! URCalendarCell
        newCell.dateLabel.text = cellState.text
        newCell.setupApperance()
        self.handleCellSelected(view: newCell, cellState: cellState)
        self.handleCellTextColor(view: newCell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: self.cellIdentifier, for: indexPath) as! URCalendarCell
        cell.dateLabel.text = cellState.text
        cell.setupApperance()
        self.handleCellSelected(view: cell, cellState: cellState)
        self.handleCellTextColor(view: cell, cellState: cellState)
        
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        self.handleCellSelected(view: cell, cellState: cellState)
        self.handleCellTextColor(view: cell, cellState: cellState)

        if let selectedIndex = URBookDataManager.sharedInstance.getIndexOfDate(date: cellState.date), !URBookDataManager.sharedInstance.indexIsAlreadySelected(index: selectedIndex) {
            self.tableViewDelegate?.selectDate(index: selectedIndex)
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        self.handleCellSelected(view: cell, cellState: cellState)
        self.handleCellTextColor(view: cell, cellState: cellState)
        
        if let selectedIndex = URBookDataManager.sharedInstance.getIndexOfDate(date: cellState.date) {
            self.tableViewDelegate?.deselectDate(index: selectedIndex)
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        let date = visibleDates.monthDates.first!.date
        
        self.delegate?.scrollToMonth(month: date.getMonth())
    }
    
    func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
        if URBookDataManager.sharedInstance.isItemOnDay(day: cellState.date) {
            return true
        }
        return false
    }
}
```

**Comment by gabrielcandiag** [comment] 2018-07-05 03:39
It's hard for me to provide a sample app, maybe you can give me some pointers to where the problem could be. I found very weird that the method

```
public func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        handleSelectionValueChanged(collectionView, action: .didSelect, indexPath: indexPath, selectionType: .userInitiated)
    }
```
And also `shouldSelectItemAt` it's not getting called.

**Comment by patchthecode** [comment] 2018-07-05 05:12
I cannot tell from the code you provided.
One thing i would say is, if you rebuild calendar again from scratch, you can usually tell where the problem is.

Just copy your code and create a simple calendar (an empty one), and then check the didSelect is being called. Then slowly re-add your other codes until you see it breaking. I am suggesting this route because visually, there doesnt seem to be anything wrong with your code.

**Comment by patchthecode** [comment] 2018-07-11 13:38
closing until user responds

**Closed by patchthecode** 2018-07-11 13:38 UTC
Labels: Awaiting User Input
