### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by gaurvw** [patchthecode/JTAppleCalendar#157] opened 2016-10-04 10:08 UTC
First: Good job with the library. Its pretty useful. Second: I am having a couple of layout issues with the library:

**Offset Issues:**

When I start the app for the first time, the entire calendar is shifted down. Its only when I scroll or tap the empty space, it slides back up. Here's what I mean:

When the view controller containing the calendarView is invoked:

<img width="311" alt="screen shot 2016-10-04 at 3 24 03 pm" src="https://cloud.githubusercontent.com/assets/3697070/19069980/e19e4644-8a46-11e6-9554-bff94801eec2.png">

And when I swipe across the month, its back to normal position:

<img width="310" alt="screen shot 2016-10-04 at 3 24 13 pm" src="https://cloud.githubusercontent.com/assets/3697070/19070003/f110c296-8a46-11e6-8d4e-a51a30e32c9d.png">

Why would this be happening? I am not supplying any header view or anything like that.

**Landscape Issues:** 

When I rotate the device and back and swipe the date, the calendar is sort of teleported to another year altogether. In the video link below, when I rotate and then swipe from December 2016, I end up in July 2015, which is weird. 

Link to video explanation of the issue: [YouTube](https://youtu.be/wt6Gf6Z_l3g)

Here's my code to setup the calendar:

`override func viewWillAppear(_ animated: Bool){
        initialiseCalendar()
    }
    
    func initialiseCalendar(){
        
        self.calendarView.dataSource = self
        self.calendarView.delegate = self
        self.calendarView.registerCellViewXib(fileName: "CalendarCell")
        self.calendarView.allowsMultipleSelection = false
        self.calendarView.cellInset = CGPoint(x: 0, y: 0)
        
        self.calendarView.reloadData()
        
        // After reloading. Scroll to your selected date, and setup your calendar
        calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: false, animateScroll: false) {
            // Code to set labels for current month here
        }
    }
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> (startDate: Date, endDate: Date, numberOfRows: Int, calendar: Calendar) {
        // You can set your date using NSDate() or NSDateFormatter. Your choice.
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        let currentYear = (sysCalendar as NSCalendar).component(.year, from: Date())
        
        let firstDate = formatter.date(from: "\(currentYear - 2) 01 01")
        let secondDate = formatter.date(from: "\(currentYear + 3) 01 01")
        let numberOfRows = 6
        let aCalendar = Calendar.current // Properly configure your calendar to your time zone here
        
        return (startDate: firstDate!, endDate: secondDate!, numberOfRows: numberOfRows, calendar: aCalendar)
    }
`

For reference, I'm using the Swift3 Branch.

**Comment by patchthecode** [comment] 2016-10-04 16:30
First, concerning the space above the calendar.
Check out this -> https://github.com/patchthecode/JTAppleCalendar/issues/31#issuecomment-222337818

**Comment by gaurvw** [comment] 2016-10-05 08:06
Ok so the first issue was fixed by disabling auto adjust of scroll view insets. The landscape rotation issue still persists though.

**Comment by patchthecode** [comment] 2016-10-05 09:28
Ah lol yea, that second issue I have a nice solution being worked on now.
But if you want a one line code fix in the mean time, 

look for this function:

```swift
func reloadData(checkDelegateDataSource check: Bool,
                    withAnchorDate anchorDate: Date? = nil,
                    withAnimation animation: Bool = false,
                    completionHandler:(() -> Void)? = nil)
```

That funciton can be found in the`JTAppleCalendarView.swift` file.
In that function, comment out this line

`scrollToDate(self.startOfMonthCache)`

And let me know know if its fixed. If its fixed, then you can close this issue.
But yes, this fix is being worked on for other release.

**Comment by gaurvw** [comment] 2016-10-05 13:36
Hi,

I performed the mentioned changes and it still doesn't work. Here's how the `reloadData` function looks like:

```
func reloadData(checkDelegateDataSource check: Bool, withAnchorDate anchorDate: Date? = nil, withAnimation animation: Bool = false, completionHandler:(()->Void)? = nil) {
        // Reload the datasource
        if check { reloadDelegateDataSource() }
        var layoutWasUpdated: Bool?
        if layoutNeedsUpdating {
            self.configureChangeOfRows()
            self.layoutNeedsUpdating = false
            layoutWasUpdated = true
        }
        // Reload the data
        self.calendarView.reloadData()
        
        // Restore the selected index paths
        for indexPath in theSelectedIndexPaths { restoreSelectionStateForCellAtIndexPath(indexPath) }
        
        delayRunOnMainThread(0.0) {
            let scrollToDate = {(date: Date) -> Void in
                if self.registeredHeaderViews.count < 1 {
                    self.scrollToDate(date, triggerScrollToDateDelegate: false, animateScroll: animation, completionHandler: completionHandler)
                } else {
                    self.scrollToHeaderForDate(date, triggerScrollToDateDelegate: false, withAnimation: animation, completionHandler: completionHandler)
                }
            }
            if let validAnchorDate = anchorDate { // If we have a valid anchor date, this means we want to scroll
                // This scroll should happen after the reload above
                scrollToDate(validAnchorDate)
            } else {
                if layoutWasUpdated == true {
                    // This is a scroll done after a layout reset and dev didnt set an anchor date. If a scroll is in progress, then cancel this one and
                    // allow it to take precedent
                    if !self.scrollInProgress {
                        //scrollToDate(self.startOfMonthCache)
                    } else {
                        if let validCompletionHandler = completionHandler { self.delayedExecutionClosure.append(validCompletionHandler) }
                    }
                } else {
                    if let validCompletionHandler = completionHandler {
                        if self.scrollInProgress {
                            self.delayedExecutionClosure.append(validCompletionHandler)
                        } else {
                            validCompletionHandler()
                        }
                    }
                }
            }
        }
    }
```

**Comment by patchthecode** [comment] 2016-10-05 17:34
OK, it works on my code because i have done massive changes to it.
I'll look into your problem in a bit.

**Comment by patchthecode** [comment] 2016-10-05 17:35
Also since you first issue is fix. I will close this.
Because the rotating issue is already being tracked here --> https://github.com/patchthecode/JTAppleCalendar/issues/142

cheers.

**Closed by patchthecode** 2016-10-05 17:35 UTC

**Comment by rmit-s3610584-Shuyang-Liu** [comment] 2017-10-07 06:12
Hi I have the same issue when the device rotated the date will go back to the start date of the calendar, any chance you've fixed this by now? Thank you.

**Comment by patchthecode** [comment] 2017-10-07 16:48
@rmit-s3610584-Shuyang-Liu 

```swift
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    calendarView.viewWillTransition(to: size, with: coordinator, anchorDate: dateToScrollBackTo)
}
```

**Comment by rmit-s3610584-Shuyang-Liu** [comment] 2017-10-08 00:53
Hi thank you for the help, but did you mean this one? 

calenaerView.viewWillTransition(to: size, with: coordinator, focusDateIndexPathAfterRotate:  )

because I couldn't  find the one withe the anchorDate in it.

**Comment by rmit-s3610584-Shuyang-Liu** [comment] 2017-10-08 00:57
But the problem is fixed with the focusDateIndexPathAfterRotate:, thank you very much!

**Comment by patchthecode** [comment] 2017-10-08 01:26
@rmit-s3610584-Shuyang-Liu ah ok, i thought you were using the master branch code.

Yes you can use that funciton for now, but on the next version release, it will be changed to the one i mentioned.
cheers 🍻
