### ISSUE TITLE
some cells background color change error in Swift 3

### ISSUE THREAD

**Issue by codeservis** [patchthecode/JTAppleCalendar#393] opened 2017-04-27 08:02 UTC
Hello  I want to do some cells background color change but gives mistake my question under below. This is bug ? or where can I doing mistake ?

http://stackoverflow.com/questions/43651916/jtapplecalendar-cell-background-color-change-error-in-swift-3

**Comment by patchthecode** [comment] 2017-04-27 16:29
I have posted an answer there for you.
But if you are still stuck, then please respond here.

**Comment by patchthecode** [comment] 2017-04-29 13:52
Closing, as this is an issue of the understanding of UICollectionView. Not a calendar problem.

I hope you have resolved the issue. If you still need help, then let me know.

**Comment by codeservis** [comment] 2017-05-01 08:43
https://github.com/codeservis/ExampleCalendar.  I added there zip file simple project dude, don't worked with your codes.

**Comment by patchthecode** [comment] 2017-05-01 15:25
i have fixed the error in your code
[ExampleCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/968138/ExampleCalendar.zip)

But the main problem still exists.
The problem is that you code is mixed up every where. Some parts of the code are doing the same things. A bit hard to read.

I will load up a video that will help you this evening.

**Comment by patchthecode** [comment] 2017-05-10 17:21
closing this issue.

**Closed by patchthecode** 2017-05-10 17:21 UTC
Labels: question, This is not a bug. Works as expected.
