### ISSUE TITLE
Tutorial has old information

### ISSUE THREAD

**Issue by dannyharding10** [patchthecode/JTAppleCalendar#395] opened 2017-04-28 01:24 UTC
Using version 7.0.1

I'm trying to setup JTAppleCalendar using Carthage but I'm having problems with the tutorials. It seems that the tutorial found [here](https://patchthecode.github.io/MainTutorial/) is outdated, as it refers to `JTAppleDayCellView`, `JTAppleCalendarView.registerCellViewXib`, and other things which are not found so I get compiler errors. Is there a different tutorial to be looking at? How can I get started with JTAppleCalendar? Thank you!

**Comment by patchthecode** [comment] 2017-04-28 04:45
Version 7.0 tutorials is not yet complete, but the videos here should get you started -> https://patchthecode.github.io/

Scroll down to the bottom to find videos on version 7.0

**Comment by patchthecode** [comment] 2017-04-29 14:59
closing issue.
If you still need more help then let me know.

**Closed by patchthecode** 2017-04-29 14:59 UTC
Labels: Awaiting User Input

**Comment by avicks** [comment] 2017-05-01 19:22
@patchthecode is there an ETA on when written tutorials will be available?  I'm running into some interesting errors when trying to implement the calendar via NIBs and code as opposed to a storyboard.

**Comment by patchthecode** [comment] 2017-05-02 04:37
@avicks which version? 7.0

**Comment by patchthecode** [comment] 2017-05-02 06:24
@avicks what issues are you running into?

**Comment by avicks** [comment] 2017-05-02 14:34
@patchthecode Our issue seemed to stem from attempting to set constraints on cell sizes, which would cause cells to load, briefly display (albeit improperly), and then disappear.  We've since removed the constraint and things work as expected.

Also, we moved the CalendarView directly into the View Controller in our NIB file as opposed to loading it programmatically.  We're not sure if this had any affect on things working as intended.

**Comment by patchthecode** [comment] 2017-05-02 15:14
@avicks 

>Our issue seemed to stem from attempting to set constraints on cell sizes, which would cause cells to load, briefly display (albeit improperly), and then disappear

This was a bug that was fixed :)

Please remove constraints of the cells. It should work programmatically as well as Nibs.
By the way, the latest version is 7.0.2

As a side note, if you have any weird issue with the library.. _ANY_ weird issue at all; even something as simple as causing cells to briefly load then disappear, then please open an issue, because it is a bug. I check my issues every 3 hrs and I try to fix them all.

If you encounter any issue in programmatic loading, then do let me know.

**Comment by patchthecode** [comment] 2017-05-02 15:15
@avicks the cells loading issue was fixed in version 7.0.2
See the [ChangeLog](https://github.com/patchthecode/JTAppleCalendar/blob/master/CHANGELOG.md#702) here
