### ISSUE TITLE
How to deselect a selected date cell without using 'allowsMultipleSelection' 

### ISSUE THREAD

**Issue by ekchhuon** [patchthecode/JTAppleCalendar#1074] opened 2019-06-26 17:01 UTC
**(Required) Version Number:**

## Description
I am working on a single selection [not multiple selection] and I could not find the way out for deselecting of a selected cell. I could do it only if i use `calendarView.allowsMultipleSelection = true` , however; I don't need that. Any help please. I got stuck with for quite so long!!

**Comment by ekchhuon** [comment] 2019-06-28 01:16
I think I am using the wrong library. When I get stuck nobody else could solve me! bad me!

**Comment by patchthecode** [comment] 2019-06-28 01:33
can you join me here?
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment] 2019-06-28 01:39
```swift
calendarView.deselectAllDates()
```

Does this not work for you?

**Comment by ekchhuon** [comment] 2019-06-28 01:47
> ```swift
> calendarView.deselectAllDates()
> ```
> 
> Does this not work for you?

I just unable to deselect a selected cell without using `calendarView.allowsMultipleSelection = true`. Let me try your solution. Thank for your help!! :)

**Comment by patchthecode** [comment] 2019-06-28 01:51
ok.
If there are any functions you do not know, check out the `UserInteractionFunctions.swift` file it has 90% of all the functions that developers are able to do with this library.

Here are some of the deselect functions
```swift
        calendarView.deselect(dates: [date1, date2, date3] )
        calendarView.deselectAllDates()
        calendarView.deselectDates(from: date1, to: date2)
```

**Comment by ekchhuon** [comment] 2019-06-28 01:53
> ok.
> If there are any other functions you do not know, check out the `UserInteractionFunctions.swift` file it has 90% of all the functions that developers are able to do with this library.
> 
> Here are some of the deselect functions
> 
> ```swift
> calendarView.deselect(dates: [date1, date2, date3] )
> calendarView.deselectAllDates()
> calendarView.deselectDates(from: date1, to: date2)
> ```

So kind of you thanks

**Comment by patchthecode** [comment] 2019-06-28 01:57
However, if you are using version 7.1.7, you should use deselectAllDates, because the other functions had a bug (which was fixed on master branch).
If you are using master branch however, the problem is already resolved there. I will be releasing master branch soon. Have a good one.

**Comment by ekchhuon** [comment] 2019-06-28 01:58
> However, if you are using version 7.1.7, you should use deselectAllDates, because the other functions had a bug (which was fixed on master branch).
> If you are using master branch however, the problem is already resolved there. I will be releasing master branch soon. Have a good one.

Noted with thanks! :)

**Closed** 2019-07-09 02:44 UTC
