### ISSUE TITLE
Unexpected Behaviour: Automatically goes back to previous month when selecting a date in current month.

### ISSUE THREAD

**Issue by ai323** [patchthecode/JTAppleCalendar#358] opened 2017-03-25 16:27 UTC
Hey Jay,

I recently came across your JTAppleCalendar library and it is definitely awesome! However, when I was trying to implement it following your tutorial part 1 & 2, I noticed something unexpected:

![calendar_test](https://cloud.githubusercontent.com/assets/17865898/24324083/bfd4b858-11ba-11e7-8602-86c3a20647df.gif)

This issue always happens when I first launched the app in simulator and afterwards, it works perfectly. But if you launch the app again, the problem comes back.

Any help is much appreciated!

**Comment by patchthecode** [comment] 2017-03-25 20:11
What version of the calendar are you using?
This was a bug that was fixed.

If you are still experiencing the bug, and you are using version 6.1.5, then is it possible that you can zip the project you have done and send it to me? You can drop the zip file directly inside this chat box.

**Comment by ai323** [comment] 2017-03-26 03:55
Hey Jay,

It is truly amazing to get your response this fast! Here is my project file:

[Avail.zip](https://github.com/patchthecode/JTAppleCalendar/files/870554/Avail.zip)

Thanks a ton!

**Comment by patchthecode** [comment] 2017-03-26 06:32
Updated the code.
Can you check to see if your code was fixed on master branch?
Follow the instructions here -> https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by ai323** [comment] 2017-03-26 12:28
Man, problem solved! Thanks for the help!!!

**Comment by patchthecode** [comment] 2017-03-29 04:16
closing issue
released 6.1.6

**Closed by patchthecode** 2017-03-29 04:16 UTC
Labels: Already Fixed on Master Branch, bug

**Comment by mikasR** [comment] 2017-09-22 10:13
Hey,

I know this issue has been closed, however i'm having this same issue on version 6.1.6.
Can you point me to the solution, because i really don't want to upgrade to version 7.

Thank you.

**Comment by patchthecode** [comment] 2017-09-22 14:59
@mikasR Hey here is the reason why I am try to get every one to upgrade to version 7.

right now you are using version 6.1.6
Since after this version, there has been version `7.0.0`, `7.0.1`, `7.0.2`, `7.0.3`, `7.0.4`, `7.0.5`, `7.0.6` and finally im currently fixing issues in `7.1.0`

All these version has fixed bugs/ and have gotten new enhancements, with massive code changes. I am only one person. At most, i can move between about 2 versions back. But to maintain code 8 versions back is not possible.

I understand it can be rough when updating to a new version, but seeing as there are so many issues that have been fixed in the following versions as well as major code changes, if you let me know a reason why 7.0 cannot work for you, then I can do an update that can make it work for you.

**Comment by mikasR** [comment] 2017-09-22 16:43
Thank you for the quick response.

I understand what you said. The reason i didn't want to upgrade to version 7, is because if i do so, i'll have to rewrite all my views and classes that are already in place, because of the changes made in v7. I'm also in a one person project.

I didn't want you to reopen version 6.1.6. Since this issue was closed before, i was only hoping that you could point me in the right direction to where was the source of this problem, and then maybe i could fix it myself. But for that i really would need your help to tell me where in the code does this happen, if you still remember it or have that information, of course.

Thanks

**Comment by patchthecode** [comment] 2017-09-22 17:05
OK, can you tell me what you have in your pod file for JTAppleCalendar?
let me see what i can do.

**Comment by patchthecode** [comment] 2017-09-22 17:06
Also, is it possible that you have some sample app that can reproduce this?

**Comment by mikasR** [comment] 2017-09-25 08:40
Hi, in my podfile i have the following:
pod 'JTAppleCalendar', '~> 6.1.6'

I don't have a sample, but i'll make one and will post it here.

**Comment by mikasR** [comment] 2017-09-25 09:25
Hi again,

I tried making a sample, but with swift 4 and calendar version 6.1.6, i have build errors.

However, this issue happens on version 6.1.6, on the sample provided here --> https://github.com/orazz/CalendarPopUp
