### ISSUE TITLE
Dates are randomly placed when using scrollToDate() method

### ISSUE THREAD

**Issue by HassanSE** [patchthecode/JTAppleCalendar#644] opened 2017-12-01 10:11 UTC
I'm using version 7.1.4 and having this issue that upon using `scrollToDate()` method to scroll to current date, the previous/next months dates are randomly placed. To get a better idea, here's how it looks:

![simulator screen shot - iphone 8 - 2017-12-01 at 15 06 23](https://user-images.githubusercontent.com/14030986/33478000-9e910b1a-d6a9-11e7-89c4-d07e96ee0879.png)

You can clearly see there's something wrong with scrolling position as well. Here's what I've done:

```swift
calendarView.visibleDates { (visibleDates) in
            self.setupViewOfCalendar(from: visibleDates)
            DispatchQueue.main.async {
                self.calendarView.scrollToDate(Date())
            }
        }
```

**Comment by patchthecode** [comment] 2017-12-01 14:58
A little more information please.

Do you have this code in you view did load?
Does it happen only of first load? or does this happen every time this function is called?

**Comment by HassanSE** [comment] 2017-12-01 18:11
Well, I've following your tutorial and most of the calendar is done via IB. It happens only on first load. Once I scroll or tap calendar, it adjusts and everything gets back to correct position. Here's the code:

    override func viewDidLoad() {
        super.viewDidLoad()
        setupCalendar()
    }
    
    func setupCalendar() {
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        
        calendarView.visibleDates { (visibleDates) in
            self.setupViewOfCalendar(from: visibleDates)
            DispatchQueue.main.async {
                self.calendarView.scrollToDate(Date())
            }
        }
    }

**Comment by patchthecode** [comment] 2017-12-04 05:01
hmm.. my sample app works perfectly. I was unable to re-create your issue.

Your case would normally happen if you build your calendar via code (and not interface builder).
It happens when developers forget to set the `calendarView.scrollingMode`.
But in your case, you said you used interface builder. Any chance you got a sample app i can try?
You can zip and email it to patchthecode@gmail.com

**Comment by patchthecode** [comment] 2017-12-06 15:42
closing this until user resonds.

**Closed by patchthecode** 2017-12-06 15:42 UTC
Labels: Awaiting User Input

**Comment by HassanSE** [comment] 2017-12-30 18:28
The culprit was `Section Insets` which I setup to 5 for each side.

**Comment by patchthecode** [comment] 2017-12-30 21:29
How did you st the section insets?
I didnt know you had those until you mentioned them now.

**Comment by HassanSE** [comment] 2017-12-31 08:28
I just set them in size inspector of `collectionView`.

**Comment by patchthecode** [comment] 2017-12-31 15:48
ok so you set the size of the cell. i see.
So the problem is now solved?
