### ISSUE TITLE
Type 'UIScrollView' has no member 'DecelerationRate' ?

### ISSUE THREAD

**Issue by angelajun12** [patchthecode/JTAppleCalendar#931] opened 2018-11-01 03:43 UTC
1. PLEASE STATE THE VERSION NUMBER you are using.
7.0
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
No
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.
I have followed the first tutorial on youtube exactly (building a calendar from scratch) but I ran into multiple build errors along the lines of "Type 'UIScrollView' has no member 'DecelerationRate'" and "Type 'UICollectionView' has no member 'elementKindSectionHeader'". I am not sure what I can do to fix this as I assume the code should work? I didn't make any modifications and have installed everything that was included in the tutorial.

**Comment by patchthecode** [comment] 2018-11-01 05:30
build errors?  Sounds like a wrong version downloaded or something.

1. What iOS version are you supporting?
2. Can you paste me what you have in your podfile?

**Comment by patchthecode** [comment] 2018-11-05 14:49
The tutorial is referring to an older version.
The latest version is now 7.1.6

Can you try this in your pod file and check?

**Comment by angelajun12** [comment] 2018-11-07 23:37
I changed the podfile to indicate the newest version but I continued to receive errors. I have included a screenshot of the new (but similar type) error messages I have received. The "no such module" error appears and then sometimes disappears so I am unsure the cause of that as well...

![screen shot 2018-11-07 at 6 33 25 pm](https://user-images.githubusercontent.com/25934488/48168020-c4019580-e2bb-11e8-8174-c8ae4340cf20.png)

**Comment by angelajun12** [comment] 2018-11-08 16:29
[newCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2562580/newCalendar.zip)

Thank you for all of your help so far!

**Comment by patchthecode** [comment] 2018-11-24 17:14
So sorry for the late reply.
I thought i responded.

The problem is because 7.1.6 is for swift version 4.2
But in your pod file you have that `platform :ios, '9.0'`

If you comment it out so that it defaults to the latest version of iOS, your errors will go away

**Comment by angelajun12** [comment] 2018-11-28 21:36
Hi, 
Sorry for the trouble but I am still receiving the same error after commenting that line out.

I thought perhaps there was a different issue so I tried for a third time to create a new project and install the pod (using 7.1.6 and commenting out the ios) but I am still receiving the same multiple "No such module 'JTAppleCalendar'", "X is not a member type of Y", and "Type X has no member Y" errors. 

I have even tried cloning your sample master project to see if that will run but even in that case I get the "not a member type" errors.

I am still using Swift 4.0, iOS 10.14.1, XCode 9.2, and JTAppleCalendar 7.1.6

**Comment by patchthecode** [comment] 2018-11-29 00:39
this cannot work

JTAppleCalendar 7.1.6, is for swift --> 4.2
If you are using that older version of swift, then you'd need to get a calendar version that works with it.

Since 4.0 was so far away, i cant even remember... maybe calendar version 7.0 ?

**Comment by angelajun12** [comment] 2018-11-29 05:01
Sorry, my mistake. I meant to say Swift 4.2.1

**Comment by patchthecode** [comment] 2018-12-19 19:15
I'll close this issue as it seems to not be related to the library, but related to versioning of either Swift, Xcode, or the Pod version.

I have come to this conclusion because when you use the solution i mention above, it works for me with a blank empty project.

**Closed** 2018-12-19 19:15 UTC
